Translate plugins/environment-plugin
line/webpack.kr pull request #14
Opened 2021-06-15 09:04 UTC by moonheekim0118

## Summary 

// Issues 링크 #12 

## 리뷰 참고 사항

- default values는 '기본값'이라고 번역했습니다. 

## Glossary

- Mapping :  매핑
- Error: 오류
-  third-party : 써드 파티 
- Bundling : 번들링
- Build : 빌드
- repository : 저장소
- environment variable :환경변수

안녕하세요, 혹시 문제되는 점이나 잘못 된 점이 있다면 알려주세요. 바로 고치도록 하겠습니다!

2021-06-15 09:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/line/webpack.kr?pullRequest=14) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/line/webpack.kr?pullRequest=14) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/line/webpack.kr?pullRequest=14) it.</sub>

2021-06-16 02:05 UTC, dkstyle commented on src/content/plugins/environment-plugin.md
> +써드 파티 [`DotenvPlugin`](https://github.com/mrsteele/dotenv-webpack) (`dotenv-webpack`) 를 사용해 [dotenv 변수](https://www.npmjs.com/package/dotenv)를 사용할 수 있습니다.
~ 를 사용해 → ~을 사용해

2021-06-16 02:05 UTC, dkstyle commented on src/content/plugins/environment-plugin.md
> +`EnvironmentPlugin` 을 사용해 [`process.env`](https://nodejs.org/api/process.html#process_process_env) 키에 [`DefinePlugin`](/plugins/define-plugin)을 간단히 적용할 수 있습니다.
조사를 띄어 쓴 경우와 붙여 쓴 경우가 섞여 있는데요. 
앞단어에 붙여쓰는 방법으로 전체적으로 통일되면 좋을 것 같습니다.

2021-06-16 02:05 UTC, dkstyle commented on src/content/plugins/environment-plugin.md
> +대안적으로, `EnvironmentPlugin`은 키에 기본값을 매핑한 객체를 지원합니다. 키가 `process.env`에 정의되지 않은 경우에는 기본값을 사용합니다.
`대안적으로` 를 `또는` 같은 표현으로 바꾸면 읽기에 더 자연스럽지 않을지 의견 드립니다.

2021-06-16 04:28 UTC, moonheekim0118 commented
리뷰해주신 부분 반영했습니다. 한번에 고쳤어야하는데 push 날린 점 죄송합니다 😭....

2021-06-16 06:33 UTC, keipark requested changes

2021-06-16 06:33 UTC, keipark commented on src/content/plugins/environment-plugin.md
> +변수가 번들링 시점에 _제공되어야 한다면_ `undefined`를 사용하고, 선택 사항이라면 `null`을 사용합니다.
새로운 줄이 추가되어 여기서부터 틀어짐이 발생합니다. 
총 줄수가 맞도록 수정 부탁드립니다 :)

2021-06-16 06:33 UTC, keipark commented on src/content/plugins/environment-plugin.md
> +W> 만약 환경변수가 번들링 시점에 발견되지 않는다면 기본값이 제공되지 않습니다. 이때 웹팩은 경고 대신 오류를 띄웁니다.
* 웹팩 → webpack 으로 번역하고 있습니다. (https://github.com/line/webpack.kr/wiki/Glossary)

2021-06-16 06:48 UTC, YukJiSoo requested changes
https://github.com/line/webpack.kr/pull/14#issuecomment-861325185
위 코멘트에서 CLA sign을 해주시면 감사하겠습니다!

2021-06-16 06:48 UTC, YukJiSoo commented on src/content/plugins/environment-plugin.md
> +T> 환경변수를 정의하지 않으면 "`EnvironmentPlugin` - `${key}` environment variable is undefined" 오류가 발생합니다.
환경변수 -> 환경 변수

2021-06-16 07:11 UTC, moonheekim0118 commented
리뷰 반영했습니다! Glossary 제대로 확인 못한 점 죄송합니다 😭

2021-06-16 08:07 UTC, YukJiSoo approved these changes

2021-06-16 09:04 UTC, keipark approved these changes

2021-06-17 23:40 UTC, choilim approved these changes

2021-06-19 11:39 UTC, merged

2021-06-19 11:39 UTC, dkstyle commented
기여해 주셔서 감사합니다 👯