add: kr translation
line/webpack.kr pull request #179
Opened 2021-08-17 01:27 UTC by yoonminsohappy

## Summary 

https://github.com/line/webpack.kr/issues/7#issuecomment-897347712

2021-08-17 09:05 UTC, choilim commented on src/content/contribute/plugin-patterns.md
> +플러그인은 웹팩 빌드 시스템 내에서 커스터마이징을 수행할 수 있는 무한한 기회를 제공합니다. 이를 통해 커스텀 애셋 유형을 생성하고, 고유한 빌드 수정을 수행할 수 있게 하며, 심지어 미들웨어를 사용하는 동안 웹팩 런타임을 향상시킬 수 있습니다. 다음은 플로그인을 작성할 때 유용하게 쓰이는 웹팩의 몇 가지 기능입니다.
`플로그인을` --> `플러그인을` 오타인거 같습니다~

2021-08-17 09:06 UTC, choilim commented on src/content/contribute/plugin-patterns.md
> +- `compilation.modules`:컴파일 결과물의 모듈(빌드된 입력) 집합입니다. 각 모듈은 소스 라이브러리의 원시 파일의 빌드를 관리합니다.
`:컴파일` -->  `: 컴파일` 띄어쓰기 부탁드려요~

2021-08-17 09:07 UTC, choilim commented on src/content/contribute/plugin-patterns.md
> +- `module.fileDependencies`: 모듈에 포함된 소스 파일 경로의 배열입니다. 이것은 자바스크립트 파일 자체(예: index.js )와 필요한 모든 의존성 자산 파일들(스타일 시트, 이미지 등)을 포함합니다. 의존성을 검토하는 것은 어떤 소스 파일이 모듈에 속하는지 파악하는데 유용합니다.
`의존성 자산 파일들` --> `의존성 애셋 파일들` 애셋으로 부탁드려요~

2021-08-17 09:08 UTC, choilim commented on src/content/contribute/plugin-patterns.md
> +- `compilation.chunks`: 컴파일의 청크 세트(빌드 출력)입니다. 각 청크는 최종 렌더링된 자산의 구성을 관리합니다.
여기도 `애셋`으로 부탁드려요~

2021-08-17 09:10 UTC, choilim commented
Assignees 지정 부탁드려요~

2021-08-17 09:26 UTC, yoonminsohappy commented on src/content/contribute/plugin-patterns.md
> +- `compilation.chunks`: 컴파일의 청크 세트(빌드 출력)입니다. 각 청크는 최종 렌더링된 자산의 구성을 관리합니다.
리뷰 감사드립니다! 코멘트 주신 부분 전부 반영하였습니다. 감사합니다!

2021-08-17 09:29 UTC, choilim approved these changes

2021-08-18 05:57 UTC, dkstyle requested changes

2021-08-18 05:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.md
> +플러그인은 웹팩 빌드 시스템 내에서 커스터마이징을 수행할 수 있는 무한한 기회를 제공합니다. 이를 통해 커스텀 애셋 유형을 생성하고, 고유한 빌드 수정을 수행할 수 있게 하며, 심지어 미들웨어를 사용하는 동안 웹팩 런타임을 향상시킬 수 있습니다. 다음은 플러그인을 작성할 때 유용하게 쓰이는 웹팩의 몇 가지 기능입니다.
웹팩은 영문 webpack 그대로 표기합니다.

2021-08-18 05:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.md
> +              // 우리는 지금 소스 구조에 대해 많은 것을 배웠습니다...
(WE, YOU, SHE, HE등의 인칭대명사는 번역하지 않습니다.)
우리는 지금 소스 구조에 대해 많은 것을 배웠습니다...
-> 이제 소스 구조에 대해 많은 것을 배웠습니다...

2021-08-18 05:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.md
>  W> **Deprecation warning**: Array functions will still work.
이 부분 번역이 누락되었습니다.

2021-08-18 05:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.md
>  W> **Deprecation warning**: Array functions will still work.
이 부분 번역이 누락되었습니다.

2021-08-18 06:00 UTC, dkstyle commented
공식 문서 최신 내용 반영을 통해 plugin-patterns.md 파일이 plugin-patterns.mdx로 변경되었습니다.
kr upstream 브랜치를 fork 브랜치에 한번 머지한 후 수정사항과 함께 다시 확인 부탁드립니다.

2021-08-18 07:03 UTC, dkstyle commented on src/content/contribute/plugin-patterns.md
> +              // 이제 소스 구조에 대해 많은 것을 배웠습니다...ㄴ
수정 과정에서 뒤에 오타가 들어간것 같습니다.

2021-08-18 07:53 UTC, yoonminsohappy commented
> 공식 문서 최신 내용 반영을 통해 plugin-patterns.md 파일이 plugin-patterns.mdx로 변경되었습니다.
> kr upstream 브랜치를 fork 브랜치에 한번 머지한 후 수정사항과 함께 다시 확인 부탁드립니다.

@dkstyle 
1. 코멘트 감사합니다! 리뷰 주신 부분 반영하였습니다. 
2. kr upstream branch 를 -> fork branch 에 머지하였습니다. 기존 .md 확장자 파일은 삭제하였습니다.

제가 이해한 것이 맞는지 코멘트 부탁드립니다! 감사합니다!

2021-08-18 08:55 UTC, dkstyle commented
> > 공식 문서 최신 내용 반영을 통해 plugin-patterns.md 파일이 plugin-patterns.mdx로 변경되었습니다.
> > kr upstream 브랜치를 fork 브랜치에 한번 머지한 후 수정사항과 함께 다시 확인 부탁드립니다.
> 
> @dkstyle
> 
> 1. 코멘트 감사합니다! 리뷰 주신 부분 반영하였습니다.
> 2. kr upstream branch 를 -> fork branch 에 머지하였습니다. 기존 .md 확장자 파일은 삭제하였습니다.
> 3. (질문) `line/webpack.kr 레포의 kr 브랜치`와 `fork 레포의 작업 브랜치` 의 싱크를 맞추면 되는건가요?
> 
> 제가 이해한 것이 맞는지 코멘트 부탁드립니다! 감사합니다!

@yoonminsohappy 현재 line/webpack.kr의 최신 상태와 맞추어 주시면 됩니다. 잘하셨습니다 :) 
md -> mdx file로 rename 된 것이기때문에, 별도로 삭제를 하지 않으셔도 올바르게 트래킹이 됩니다. 결과적으로는 md파일은 제거되고 mdx 파일만 남는것이 맞습니다.
최신 내용 반영 과정에서 컨텐츠가 추가되어서 추가로 번역 해야할 내용들이 있습니다. 확인 부탁드립니다.

2021-08-18 08:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.mdx
>  T> The `fileDependencies` `Set` is rebuilt in each compilation, so your plugin must add its own watched dependencies into each compilation to keep them under watch.
추가된 컨텐츠 번역 부탁드립니다.

2021-08-18 08:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.mdx
>  W> Since webpack 5, `compilation.fileDependencies`, `compilation.contextDependencies` and `compilation.missingDependencies` are now a `Set` instead of a `Sortable Set` and thus no longer sorted.
추가된 컨텐츠 번역 부탁드립니다.

2021-08-18 08:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.mdx
>  W> **Deprecation warning**: Array functions will still work.
번역 누락된 내용 작업 부탁드립니다.

2021-08-18 08:57 UTC, dkstyle commented on src/content/contribute/plugin-patterns.mdx
>  W> **Deprecation warning**: Array functions will still work.
번역 누락된 내용 작업 부탁드립니다.

2021-08-18 09:09 UTC, dkstyle commented on src/content/contribute/plugin-patterns.mdx
> +W> **Deprecation warning**: 배열 함수는 계속 작동할 것입니다.
기술문서에서의 will의 경우 ~할 것이다. 보다는 ```배열 함수는 계속 동작합니다``` 와 같이 표현하는 것이 더 적합해 보입니다.
참고: https://blog.daum.net/standards/450

2021-08-18 09:29 UTC, yoonminsohappy commented on src/content/contribute/plugin-patterns.mdx
> +W> **Deprecation warning**: 배열 함수는 계속 작동할 것입니다.
아하 그렇군요! 반영하였습니다!

2021-08-18 09:38 UTC, yoonminsohappy commented
> @yoonminsohappy 현재 line/webpack.kr의 kr브랜치 상태와 맞추어 주시면 됩니다. 잘하셨습니다 :)
> 
> md -> mdx file로 rename 된 것이기때문에, 별도로 삭제를 하지 않으셔도 kr브랜치 내용을 반영하셨다면, 올바르게 트래킹이 됩니다. 결과적으로는 md파일은 제거되고 mdx 파일만 남는것이 맞습니다.
> 
> 최신 내용 반영 과정에서 컨텐츠가 추가되어서 추가로 번역 해야할 내용들이 있습니다. 확인 부탁드립니다.

리뷰 감사드립니다!

fetch upstream & merge upstream 을 했습니다. 그런데 리뷰 주신 4가지 부분(추가 컨텐츠 번역, 누락된 부분 번역)이 확인되지 않는 걸 보니, 올바르게 반영되지 않은 것 같습니다. 

이 4가지 부분에 대한 반영은 조금 기다려주시면 감사하겠습니다! fork 브랜치가 최신화된 것인지 확인해 본 후 반영해보겠습니다.

2021-08-19 01:04 UTC, dkstyle approved these changes

2021-08-27 02:11 UTC, keipark commented on src/content/contribute/plugin-patterns.mdx
> +T> `fileDependencies` `Set` 는 각 컴파일 결과물 내에서 다시 빌드되므로, 플러그인은 감시를 유지하기 위해 각 컴파일 결과물 자체에 감시된 의존성을 추가해야 합니다.
자연스럽게 읽힐 수 있도록 조사를 바꿔주면 좋겠습니다~
`Set 는` → `Set 은`

2021-09-02 08:46 UTC, yoonminsohappy commented on src/content/contribute/plugin-patterns.mdx
> +T> `fileDependencies` `Set` 는 각 컴파일 결과물 내에서 다시 빌드되므로, 플러그인은 감시를 유지하기 위해 각 컴파일 결과물 자체에 감시된 의존성을 추가해야 합니다.
피드백 감사합니다! 반영하도록 하겠습니다 :)

2021-09-08 04:32 UTC, keipark approved these changes

2021-09-08 04:37 UTC, YukJiSoo approved these changes

2021-09-08 04:45 UTC, merged