feat(docs): Translate plugins/common-chunk-plugin.md
line/webpack.kr pull request #23
Opened 2021-06-20 10:18 UTC by 1ilsang

## Summary 

https://github.com/line/webpack.kr/issues/22

`plugins/common-chunk-plugin.md`

## Glossary

```md
opt-in opt-in
string 문자열
records 레코드
lib 라이브러리
```

2021-06-21 02:06 UTC, YukJiSoo requested changes

2021-06-21 02:06 UTC, YukJiSoo commented on src/content/plugins/commons-chunk-plugin.md
> +W> CommonsChunkPlugin 은 webpack v4(legato)에서 제거되었습니다. 최신 버전에서 청크가 처리되는 방식을 알아보려면 [SplitChunksPlugin](/plugins/split-chunks-plugin/)를 확인하세요.
SplitChunksPlugin를 -> SplitChunksPlugin을

2021-06-21 02:06 UTC, YukJiSoo commented on src/content/plugins/commons-chunk-plugin.md
> +      // (청크에 다른 이름을 지정하십시오)
십시오 -> 세요

2021-06-21 02:06 UTC, YukJiSoo commented on src/content/plugins/commons-chunk-plugin.md
> +  // (청크를 선택하거나 모든 청크를 생략하십시오)
십시오 -> 세요

2021-06-21 02:06 UTC, YukJiSoo commented on src/content/plugins/commons-chunk-plugin.md
> +webpack 부트스트랩 로직을 별도의 파일로 추출하려면 `entry`로 정의되어 있지 않은 `name`에 `CommonsChunkPlugin`을 사용하십시오. 자세한 내용은 [캐싱 가이드](/guides/caching)를 참조하세요.
십시오 -> 세요

2021-06-21 05:01 UTC, YukJiSoo approved these changes

2021-06-22 07:54 UTC, dkstyle commented on src/content/plugins/commons-chunk-plugin.md
> +`CommonsChunkPlugin` 은 여러 엔트리 포인트 간에 공유되는 공통 모듈로 이루어진 별도의 파일(청크라고 합니다)을 만드는 opt-in 기능입니다.
조사는 앞단어에 붙여주시면 좋을것 같습니다. (다른 부분을 확인해 보니 붙여쓴 곳도 있고 띄어쓴 곳도 있습니다.)
ex) `CommonChunkPlugin` 은 --> `CommonChunkPlugin`은

2021-06-22 07:54 UTC, dkstyle commented on src/content/plugins/commons-chunk-plugin.md
> +번들에서 공통 모듈을 분리한 결과로 생성된 청크 파일을 처음에 한 번 로드하고 나중에 사용하기 위해 캐시에 저장할 수 있습니다. 이로 인해 브라우저가 새 페이지를 방문할 때마다 더 큰 번들을 로드하지 않고 캐시에서 공유 코드를 빠르게 제공할 수 있으므로 페이지 속도가 최적화 됩니다.
최적화 됩니다. -> 최적화됩니다.

2021-06-22 07:54 UTC, dkstyle commented on src/content/plugins/commons-chunk-plugin.md
> +  // `true`이면 새로운 비동기 공통 청크가 `options.name`의 하위 항목과 `options.chunks`의 형제 항목으로 생성됩니다.
child를 하위 항목으로 표현한건 괜찮은 것 같은데요. 뒤에 형제 항목이라고 오는 부분도 비슷한 표현으로 바꾸면 어떨까요?

2021-06-23 02:51 UTC, limong commented on src/content/plugins/commons-chunk-plugin.md
> +  // 이는 청크 이름으로 사용됩니다.
윗 문장이랑 연결되어야 할 것 같습니다.

2021-06-23 02:51 UTC, limong commented on src/content/plugins/commons-chunk-plugin.md
> +  // 생략하고 `options.async` 또는 `options.children`이 설정되면 모든 청크가 사용됩니다. 그렇지 않으면 `options.filename`이 사용됩니다.
```생략하`면` `options.async` 또는 `options.children`이 설정되`고` 모든 청크가 사용됩니다.```
미묘하지만 [아래 문장](https://github.com/line/webpack.kr/pull/23/files#diff-8c4f339244ae1c17e6857473a4a7c7f9f2f7c610926c589bdb58c019618ad179R44) 처럼하는 것이 조금 더 자연스러운것 같아요

2021-06-23 04:53 UTC, choilim commented on src/content/plugins/commons-chunk-plugin.md
> +엔트리 포인트간에 공유되는 공통 모듈을 포함하는 추가 청크를 생성합니다.
띄어쓰기: '포인트간에' --> '포인트 간에'

2021-06-23 04:54 UTC, choilim commented on src/content/plugins/commons-chunk-plugin.md
> +생성된 청크는 엔트리 포인트 전에 로드해야 한다.
'로드해야 한다.' 보다는 '로드해야 합니다.'로 문장을 마무리하는게 더 자연스러운거 같습니다~

2021-06-23 06:30 UTC, keipark requested changes

2021-06-23 06:30 UTC, keipark commented on src/content/plugins/commons-chunk-plugin.md
> +      //  들어 가지 않습니다)
`들어 가지` → `들어가지` 띄어쓰기 수정이 필요합니다

2021-06-23 06:30 UTC, keipark commented on src/content/plugins/commons-chunk-plugin.md
> +- [공용 및 Vendor 청크](https://github.com/webpack/webpack/tree/master/examples/common-chunk-and-vendor-chunk)
공용 vs 공통 한가지로 통일하면 어떨까요?

2021-06-23 06:30 UTC, keipark commented on src/content/plugins/commons-chunk-plugin.md
> +  // 공통 청크의 파일 이름 템플릿 입니다. `output.filename`과 동일한 플레이스홀더를 포함할 수 있습니다.
템플릿 입니다. → 템플릿입니다 
띄어쓰기 수정이 필요합니다

2021-06-23 06:30 UTC, keipark commented on src/content/plugins/commons-chunk-plugin.md
> +  // 이름을 변경할 수 있습니다.
instead of `true` 부분이 문장에서 빠진 것 같습니다~
번역에 맞게 줄바꿈 하실때 자연스럽게 끊어지게 해도 좋을 것 같습니다 :)
```
예)
// ...문자열을 제공해
// 출력 파일의 이름을 변경할 수 있습니다.
```

2021-06-24 14:17 UTC, dkstyle commented on src/content/plugins/commons-chunk-plugin.md
> +W> CommonsChunkPlugin 은 webpack v4(legato)에서 제거되었습니다. 최신 버전에서 청크가 처리되는 방식을 알아보려면 [SplitChunksPlugin](/plugins/split-chunks-plugin/)을 확인하세요.
조사는 앞단어에 붙여주시면 좋을것 같습니다. (다른 부분을 확인해 보니 붙여쓴 곳도 있고 띄어쓴 곳도 있습니다.)
ex) CommonChunkPlugin 은 --> CommonChunkPlugin은

전체적으로 한번 확인 부탁드립니다.

2021-06-25 11:26 UTC, 1ilsang commented on src/content/plugins/commons-chunk-plugin.md
> +W> CommonsChunkPlugin 은 webpack v4(legato)에서 제거되었습니다. 최신 버전에서 청크가 처리되는 방식을 알아보려면 [SplitChunksPlugin](/plugins/split-chunks-plugin/)을 확인하세요.
@dkstyle 
수정했습니다. 감사합니다!

2021-06-26 10:16 UTC, hg-pyun commented on src/content/plugins/commons-chunk-plugin.md
> +위에서 볼 수 있듯이 이 예제를 사용하면 함수 내의 모든 조건이 충족되는 경우에만 하나의 라이브러리를 별도의 파일로 이동할 수 있습니다.
호흡이 긴 문장은 쉼표를 넣어주면 좋을 것 같아요.
```suggestion
위에서 볼 수 있듯이 이 예제를 사용하면 함수 내의 모든 조건이 충족되는 경우에만, 하나의 라이브러리를 별도의 파일로 이동할 수 있습니다.
```

2021-06-26 10:16 UTC, hg-pyun commented on src/content/plugins/commons-chunk-plugin.md
> +이 옵션은 CommonsChunk 알고리즘이 모듈을 이동할 위치를 결정하는 방법을 세밀하게 제어하려는 경우에 유용합니다.
```suggestion
이 옵션은 CommonsChunk 알고리즘을 통해 모듈을 이동할 위치를 결정하는 방법을 세밀하게 제어하려는 경우에 유용합니다.
```

2021-06-30 06:09 UTC, keipark approved these changes

2021-06-30 06:56 UTC, dkstyle approved these changes

2021-06-30 06:56 UTC, merged