Translate contribute/writing-a-plugin.mdx
line/webpack.kr pull request #329
Opened 2021-10-10 16:12 UTC by kwYoohae

## Summary 

#7 

## 리뷰 참고 사항

`compiler`와 `compilation`은 특정 객체를 지칭하는 말 같아서 번역을 하지 않았습니다. 

## Glossary

```
prototype: 프로토타입
event: 이벤트
third-party developers: 서드 파티 개발자들
hook: 훅 
```

2021-10-10 16:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/line/webpack.kr?pullRequest=329) <br/>All committers have signed the CLA.

2021-10-11 10:21 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +          // 모든 애셋을 거쳐 반복하고 Markdown 파일로 내용을 생성합니다.
번역이후 원문의 변경사항을 추적하기 위해, 가능하면 원문의 라인을 그대로 유지한채로 번역하는 것이 좋습니다. (다만 번역과정에서 translator 항목이 추가되기 때문에 원문과 번역 내용은 Line 수가 2씩 차이가 생깁니다.)

------
// 모든 애셋을 거쳐 반복하고 
// Markdown 파일로 내용을 생성합니다.

2021-10-11 10:22 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +이렇게 하면 다음과 같은 이름을 가진 마크다운 파일이 생성됩니다.
가능하면 라인 유지 부탁드립니다.

2021-10-11 10:51 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +이렇게 하면 다음과 같은 이름을 가진 마크다운 파일이 생성됩니다.
라인 변경과 원문과 다른 라인에 대해서 수정 완료했습니다.
지적 감사합니다. 😄

2021-10-11 23:49 UTC, dkstyle approved these changes

2021-10-11 23:49 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 `apply`라는 프로토타입 메소드로 인스턴스 화 된 객체이다. 이러한 `apply` 메소드는 플러그인을 설치하는 동안 webpack 컴파일러에 의해 한번 호출이 된다. `apply` 메소드는 컴파일러 callback에 대해 접근 권한을 부여하는 기본 webpack 컴파일러에 의해 참조된다. 플러그인의 구조는 다음과 같다.
경어를 기본으로 합니다. 
호출이 된다 -> 호출됩니다.
참조된다 -> 참조됩니다.

2021-10-11 23:49 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +  플러그인 핸들러 함수는 `(err?: Error) -> void` 서명이 있는 callback 함수와 모든 arguments가 호출된다. 핸들러 함수는 등록된 순서대로 호출 됩니다. `callback`은 모든 핸들러가 호출되고 난 뒤 호출됩니다.
호출된다. -> 호출됩니다.

2021-10-11 23:49 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +  플러그인 핸들러 함수는  `(err: Error, nextValue: any) -> void.` 서명이 있는 callback 함수와 현재 값으로 호출된다. `nextValue`가 호출되면 다음 핸들러의 현재 값이 됩니다. 첫 번째 핸들러의 현재 값은 `init`이다. 모든 핸들러가 적용된 후 callback은 마지막 값으로 호출됩니다. 만약 어떤 핸들
호출된다. -> 호출됩니다.

2021-10-11 23:49 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +  - `callAsync(...params)` 메소드를 사용하여 호출됩니다.
원문의 공백라인이 제거되었습니다.

2021-10-12 00:17 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +  - `callAsync(...params)` 메소드를 사용하여 호출됩니다.
공백 라인 복구 완료했습니다 😄

2021-10-12 01:40 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 서드파티 개발자들에게 webpck 엔진의 모든 잠재력을 보여준다. 단계별로 빌드 callback을 사용하여 개발자들은 webpack의 빌드 프로세스에 자신만의 행동을 도입할 수 있습니다. 플러그인을 빌드하는 것은 로더를 빌딩 하는 것보다 조금 더 진보되었습니다. 왜냐하면, 플러그인은 몇몇 webpack의 low-level에 내장된 hook을 이
`hook`은 다른 번역 파일에선 `훅`으로 통일하고 있습니다~

2021-10-12 01:41 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +- JavaScript function or a JavaScript class로 이름을 붙입니다.
`or a` 의 번역이 안된 것 같습니다~

2021-10-12 01:43 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인 옵션을 통해 전달되는 옵션의 유효성을 확인하려면 [`schema-utils`](https://github.com/webpack/schema-utils)를 사용하라 다음은 사용 예제입니다.
`를 사용하라` --> `를 사용하세요.` 처럼 번역하는게 좋을거 같습니다~

2021-10-12 01:44 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인 개발 중 가장 중요한 두 개의 리소스는 [`compiler`](/api/node/#compiler-instance) 과  [`compilation`](/api/compilation-hooks/) 객체입니다. 이 두 가지의 역할을 이해하는 것은 webpack 엔진을 확장하는데 첫 번째 단계입니다.
`확장하는데 첫 번째 단계` --> `확장하는 첫 번째 단계` 가 좀 더 자연스러울 것 같습니다~

2021-10-12 01:45 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 서드파티 개발자들에게 webpck 엔진의 모든 잠재력을 보여준다. 단계별로 빌드 callback을 사용하여 개발자들은 webpack의 빌드 프로세스에 자신만의 행동을 도입할 수 있습니다. 플러그인을 빌드하는 것은 로더를 빌딩 하는 것보다 조금 더 진보되었습니다. 왜냐하면, 플러그인은 몇몇 webpack의 low-level에 내장된 hook을 이
이 부분 해당 파일의 다른 부분에서도 `hook`으로 번역한 부분 다시한번 확인 부탁드립니다!!

2021-10-12 01:49 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +T> [`processAssets`](/api/compilation-hooks/#processassets) hook은 지정한 단계를 실행하기 전에 다른 플러그인에 의하여 추가된 애셋 뿐만 아니라 나중에 추가된 애셋을 가로챌 수도 있는 `additionalAssets` 프로퍼티도 지원합니다. 이는 compilation의 일부분인 애셋을 완전히 가로 챌 수도
`이는 일반적으로` 다음에 띄어쓰기가 두 번 들어간 것 같습니다~

2021-10-12 01:53 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 서드파티 개발자들에게 webpck 엔진의 모든 잠재력을 보여준다. 단계별로 빌드 callback을 사용하여 개발자들은 webpack의 빌드 프로세스에 자신만의 행동을 도입할 수 있습니다. 플러그인을 빌드하는 것은 로더를 빌딩 하는 것보다 조금 더 진보되었습니다. 왜냐하면, 플러그인은 몇몇 webpack의 low-level에 내장된 hook을 이
`compiler-hooks.mdx` 등에서 `hook`을 `훅`으로 사용한 것 확인 했습니다 고치도록 하겠습니다 😄

2021-10-13 04:52 UTC, choilim commented on src/content/contribute/writing-a-plugin.mdx
> +      //이제 우리는 컴파일을 통해 이용할 수 있는 다양한 훅들을 이용할 수 있습니다.
사소한 부분이지만.. `//` 다음에 띄어쓰기 하나가 빠진 것 같습니다~

2021-10-13 04:52 UTC, choilim approved these changes

2021-10-13 06:19 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +      //이제 우리는 컴파일을 통해 이용할 수 있는 다양한 훅들을 이용할 수 있습니다.
확인 완료했습니다. 코드안의 주석에 대해 다른 부분에서도 띄어쓰기 빠져있는지 검토후 커밋완료했습니다. 😄

2021-10-13 12:25 UTC, dkstyle requested changes

2021-10-13 12:25 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +일단 우리가 webpack compiler와 각각의 개별적인 compilations를 이해 할 수 있게 되면, engine 자체로 할 수 있는 가능성이 무궁무진해집니다. 기존 파일을 다시 포맷하거나 파생 파일을 만들거나 완전히 새로운 애셋을 만들 수 있습니다.
번역규칙에 WE, YOU, SHE, HE등의 인칭대명사는 번역하지 않습니다.

2021-10-13 12:25 UTC, dkstyle commented on src/content/contribute/writing-a-plugin.mdx
> +      // 이제 우리는 컴파일을 통해 이용할 수 있는 다양한 훅들을 이용할 수 있습니다.
번역규칙에 WE, YOU, SHE, HE등의 인칭대명사는 번역하지 않습니다.

2021-10-13 13:46 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +      // 이제 우리는 컴파일을 통해 이용할 수 있는 다양한 훅들을 이용할 수 있습니다.
다른 부분도 확인하고 수정 완료했습니다. 감사합니다. 😄

2021-10-14 00:43 UTC, dkstyle approved these changes

2021-10-18 01:06 UTC, YukJiSoo requested changes

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 서드파티 개발자들에게 webpck 엔진의 모든 잠재력을 보여준다. 단계별로 빌드 callback을 사용하여 개발자들은 webpack의 빌드 프로세스에 자신만의 행동을 도입할 수 있습니다. 플러그인을 빌드하는 것은 로더를 빌딩 하는 것보다 조금 더 진보되었습니다. 왜냐하면, 플러그인은 몇몇 webpack의 low-level에 내장된 훅을 이해할
webpck -> webpack

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 서드파티 개발자들에게 webpck 엔진의 모든 잠재력을 보여준다. 단계별로 빌드 callback을 사용하여 개발자들은 webpack의 빌드 프로세스에 자신만의 행동을 도입할 수 있습니다. 플러그인을 빌드하는 것은 로더를 빌딩 하는 것보다 조금 더 진보되었습니다. 왜냐하면, 플러그인은 몇몇 webpack의 low-level에 내장된 훅을 이해할
보여준다 -> 보여줍니다

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +Webpack용 plugin은 다음과 같이 구성됩니다.:
문장 끝의 `:`을 빼주세요!

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +- 특정한 [event hook](/api/compiler-hooks/) 로 지정합니다.
로 -> 으로
hook은 훅으로 번역하고 있습니다!

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인은 `apply`라는 프로토타입 메소드로 인스턴스 화 된 객체입니다. 이러한 `apply` 메소드는 플러그인을 설치하는 동안 webpack 컴파일러에 의해 한번 호출됩니다. `apply` 메소드는 컴파일러 callback에 대해 접근 권한을 부여하는 기본 webpack 컴파일러에 의해 참조됩니다. 플러그인의 구조는 다음과 같습니다.
`인스턴스 화` 는 `인스턴스화`로 붙여도 될 것 같아요!

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +        stats /* 훅이 탭이 끝나면 stats는 인자로 통과됩니다.*/
`훅이` 를 `훅의` 또는 다른 구조로 바꾸는게 어떨까요?? 현재 번역된 문장이 어색하게 읽혀져서요!

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인 개발 중 가장 중요한 두 개의 리소스는 [`compiler`](/api/node/#compiler-instance) 과  [`compilation`](/api/compilation-hooks/) 객체입니다. 두 가지의 역할을 이해하는 것은 webpack 엔진을 확장하는 첫 번째 단계입니다.
`compiler 과`-> `compiler 와`

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +  - `call(...params)` 메소드를 사용하여 호출됩니다..
호출됩니다.. -> 호출됩니다.

2021-10-18 01:06 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +  여기서 각각 플러그인은 이전 플러그인의 반환 값으로부터 arguments를 차례로 호출합니다. 플러그인은 실생 순서를 반드시 고려해야합니다.
실생 순서를 -> 실행 순서를

2021-10-18 01:40 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +- 특정한 [event hook](/api/compiler-hooks/) 로 지정합니다.
혹시 `[event hook]` 의 `hook` 말씀이신가요? 다른 부분의 `[]`부분도 모두 번역해야 할까요?
피드벡 감사합니다!

2021-10-18 01:44 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +- 특정한 [event hook](/api/compiler-hooks/) 로 지정합니다.
넵!

2021-10-18 02:57 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +- 특정한 [event hook](/api/compiler-hooks/) 로 지정합니다.
[`event hook`] -> [`이벤트 훅`]
[`plugins API`] -> [`플러그인 API`]로 변경했습니다.

나머지
[`schema-utils`]와 [`compiler`], [`compilation'],[`processAssets`]에 대해서는 특정 개체를 지정하는
말인것 같아서 번역을 실시 안했는데 괜찮을까요? 

답장 감사합니다

2021-10-18 03:13 UTC, YukJiSoo commented on src/content/contribute/writing-a-plugin.mdx
> +- 특정한 [event hook](/api/compiler-hooks/) 로 지정합니다.
넵 안해줘도 읽기에 어색하지 않은 것 같습니다! 반영 감사드립니다~

2021-10-18 05:53 UTC, YukJiSoo approved these changes

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +  // `apply`를 compiler를 argument로 받는 프로토타입 메소드로 정의합니다.
전체적으로 문서내의 argument 단어 번역을 통일하면 좋을 것 같습니다 (예: L66 = 인자)

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +// schema의 옵션에 대한 객체
`options 객체에 대한 schema`가 맞을 것 같습니다~

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +  - `new SyncHook([params])`를 사용하여 정의됩니다.
여기서는 '사용하여' 는 없어도 괜찮을 것 같습니다. :) (예: `~으로 정의됩니다.`)

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +플러그인의 기본값이 적용된 후 Webpack은 설정의 기본값을 적용합니다. 이를 통해 플러그인은 고유의 기본값을 제공하고 사전에 플러그인의 설정을 만드는 방법을 제공합니다.
문장의 첫 단어가 아닌 webpack은 전부 소문자를 사용해주세요.

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +          // Markdown 파일로 내용을 생성합니다.
(L286) 처럼 Markdown = 마크다운으로 통일하면 좋을 것 같습니다~

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +          // 다른 플러그인에 의해 이미 compilation이 이미 추가됬는지 확인합니다.
`to ensure that..` 부분 원문과 약간 뜻이 다른 것 같습니다~
```
이후 애셋 처리 단계 중 하나를 사용하여 
모든 애셋이 이미 다른 플러그인에 의해 compliation에 추가되었는지 확인합니다. 
```

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +  // (이는 플러그인의 public API이다.)
번역톤을 맞추면 더 좋을 것 같습니다. :) `~입니다.`

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +    // (webpack 또는 직접적으로 어떤 심볼을 require/import 하지 마십시오.)
여기도 번역톤을 맞추면 좋을 것 같습니다~
(예: 마십시오 > `마세요`, `말아야 합니다`)

2021-10-18 07:16 UTC, keipark commented on src/content/contribute/writing-a-plugin.mdx
> +일단 webpack compiler와 각각의 개별적인 compilations를 이해 할 수 있게 되면, engine 자체로 할 수 있는 가능성이 무궁무진해집니다. 기존 파일을 다시 포맷하거나 파생 파일을 만들거나 완전히 새로운 애셋을 만들 수 있습니다.
다른 부분과 맞추면 좋을 것 같습니다.
engine > 엔진

2021-10-18 09:43 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +  - `new SyncHook([params])`를 사용하여 정의됩니다.
다른 이러한 모든 부분에 대해서 수정 완료하였습니다. 😄

2021-10-18 09:44 UTC, kwYoohae commented on src/content/contribute/writing-a-plugin.mdx
> +          // 다른 플러그인에 의해 이미 compilation이 이미 추가됬는지 확인합니다.
확실히 이상하게 번역한 것 같습니다. 지적 감사드립니다. 😄

2021-10-19 02:28 UTC, keipark approved these changes

2021-10-19 06:00 UTC, merged