Translate migrate/3.mdx
line/webpack.kr pull request #339
Opened 2021-10-11 13:01 UTC by dlwnsgud8406

## Summary 
#337

## Glossary
영어 : 해석
CLI : CLI
legacy : 레거시
uglifyjs : uglifyjs
hacks : 핵
synchronously : 동기적으로
opt-out : 옵트 아웃

2021-10-11 13:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/line/webpack.kr?pullRequest=339) <br/>All committers have signed the CLA.

2021-10-13 02:05 UTC, dkstyle requested changes
전체적으로 같은 표현인데 문장마다 번역이 다른 경우가 있습니다.

구성 -> 설정
참조 -> 참고
webpack -> webpack

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +- dlwnsgud8406
들여쓰기가 적용되지 않았습니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +T> V2와 V3 사이에 변경 사항이 훨씬 적으므로 이주가 그렇게 나쁘지 않을 것입니다. 문제가 발생하는 경우, 자세한 내용은 [the changelog](https://github.com/webpack/webpack/releases)를 참조하세요.
위에는 1에서 2로 표현했기때문에 webpack 2와 3 사이에 라고 하는 것이 일관성 있어 보입니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +T> V2와 V3 사이에 변경 사항이 훨씬 적으므로 이주가 그렇게 나쁘지 않을 것입니다. 문제가 발생하는 경우, 자세한 내용은 [the changelog](https://github.com/webpack/webpack/releases)를 참조하세요.
참조하세요. -> 참고하세요. 
해당 표현은 여러 문서에서 자주 반복되는 내용으로 `참고하세요`로 통일해서 사용하고 있습니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +위 4개의 파일들 `resolve.modules`하나로 대체되었습니다. 자세한 사용법은 [resolving](/configuration/resolve)을 참조하세요.
4개의 파일들은 어떤 내용을 번역하신건가요?

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> -This option no longer requires passing an empty string. This behavior was moved to `resolve.enforceExtension`. See [resolving](/configuration/resolve) for more usage.
`no longer requires` 표현이 있기 떄문에
`전달할 필요가 없습니다.`라고 표현되는것이 좋을 것 같습니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 옵션은 더 이상 빈 문자열을 전달하지 않습니다. 이 동작은 `resolve.enforceExtension`로 이동되었습니다. 자세한 사용법은 [resolving](/configuration/resolve) 를 참조하십시오.
참조 -> 참고

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +여기에서 여러 API가 변경되었습니다. 흔히 사용되지 않으므로 자세히 나열하지 않습니다. 자세한 내용은 [resolving](/configuration/resolve)을 참조하세요.
참조 -> 참고

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이전의 로더 구성은 로더와 그 이상의 구성이 허가되는 강력한규칙 시스템으로 대체 되었습니다.
구성 -> 설정

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`resolveLoader.moduleExtensions` 구성 옵션을 사용하여 이전 동작을 계속 선택할 수 있지만 이는 권장되지 않습니다.
구성 -> 설정

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +**webpack 1** 에서, 구성된 로더가 일치하는 파일을 기준으로 확인되어집니다. 하지만, **webpack 2** 에서는, 구성된 로더는 `context` 옵션을 기준으로 확인됩니다.
구성 -> 설정

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`webpack.optimize.DedupePlugin`은 더 이상 필요하지 않습니다. 구성에서 제거하십시오.
구성 -> 설정

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +따라서 구성에서 플러그인을 제거해야 합니다 :
구성 -> 설정

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 플러그인의 구성 변경은 주로 구문적입니다.
구성 -> 설정

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 플러그인의 구성 변경은 주로 구문적입니다.
변경은 -> 변경 사항은

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`ts` 속성이 있는 다음 구성은 더 이상 webpack 2에서 유효하지 않습니다 :
원문은 한줄인데 번역에서 줄바꿈(두줄)으로 반영되었습니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +일부 로더는 컨텍스트 정보가 필요하고 구성에서 이를 읽습니다. 이것은 장기적으로 로더 옵션을 통해 전달되어야 합니다.
원문은 한줄인데 번역에서 줄바꿈(두줄)으로 반영되었습니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +관련 옵션은 로더 문서를 참조하십시오.
원문은 한줄인데 번역에서 줄바꿈(두줄)으로 반영되었습니다.
참조 -> 참고

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +웹팩 1에서는 [`require.ensure()`](/api/module-methods/#requireensure) 를 응용 프로그램의 덩어리를 지연 로드하는 방법으로 사용할 수 있습니다 :
chunk는 `청크`로 통일해 주세요.
453, 467, 473라인에서는 청크라고 그대로 번역하신것 같습니다.

2021-10-13 02:05 UTC, dkstyle commented on src/content/migrate/3.mdx
> +Webpack은 이제 표현식에서 템플릿 문자열을 지원합니다. 이는 웹팩 구성에서 사용할 수 있음을 의미합니다 :
웹팩 -> webpack

2021-10-13 02:08 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 문제를 해결하기 위해 몇 가지 해킹을 제거할 수 있습니다 :
hack은 해킹보다는 흔히 게임에서도 `게임 핵`과 같이 표현하는 것 같습니다. `핵` 그대로 표현하는것이 어떨까요

2021-10-13 02:13 UTC, dlwnsgud8406 commented
네넵 수정하겠습니다
"chunk는 청크로 통일해 주세요.
453, 467, 473라인에서는 청크라고 그대로 번역하신것 같습니다."
라고 해주셨는데
glossary에서 chunks는 덩어리로 번역이 되있어서 그런데 그

-In webpack 1, you could use
[`require.ensure()`](/api/module-methods/#requireensure) as a method
to lazily-load chunks for your application:
+웹팩 1에서는 [`require.ensure()`](/api/module-methods/#requireensure) 를 응용
프로그램의 덩어리를 지연 로드하는 방법으로 사용할 수 있습니다 :


이 문단에서는 chunks를 청크로 번역해도 괜찮을까요??


2021년 10월 13일 (수) 오전 11:08, Dongkyun Yoo ***@***.***>님이 작성:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/content/migrate/3.mdx
> <https://github.com/line/webpack.kr/pull/339#discussion_r727642984>:
>
> >
>
> -You may remove some hacks to work around this:
>
> +이 문제를 해결하기 위해 몇 가지 해킹을 제거할 수 있습니다 :
>
>
> hack은 해킹보다는 흔히 게임에서도 게임 핵과 같이 표현하는 것 같습니다. 핵 그대로 표현하는것이 어떨까요
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/line/webpack.kr/pull/339#pullrequestreview-778023238>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMMAFXQVCTWWQJYBYF3ZCTUGTS3TANCNFSM5FYF7ULQ>
> .
>

2021-10-13 02:17 UTC, dkstyle commented
@dlwnsgud8406 `청크`가 glossary에 업데이트가 안되어있었네요.
 청크로 반영해 주시면 됩니다. glossary도 업데이트 해 두었습니다.

2021-10-13 02:19 UTC, dlwnsgud8406 commented
넵 답변해주셔서 감사합니다 !

2021년 10월 13일 (수) 오전 11:18, Dongkyun Yoo ***@***.***>님이 작성:

> @dlwnsgud8406 <https://github.com/dlwnsgud8406> 청크가 glossary에 업데이트가
> 안되어있었네요.
> 청크로 반영해 주시면 됩니다. glossary도 업데이트 해 두었습니다.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/line/webpack.kr/pull/339#issuecomment-941852656>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATMMAFRRSWSJAYSPCVA75U3UGTT5XANCNFSM5FYF7ULQ>
> .
>

2021-10-13 04:56 UTC, choilim commented on src/content/migrate/3.mdx
> +새로운 이름짓기규칙들이 이해하기 쉬워졌고 `module.rules`를 사용하도록 구성을 업그레이드 해야하는 좋은 이유입니다.
`naming conventions`은 `네이밍 컨벤션`으로 사용하는 것은 어떨까요??

2021-10-13 04:57 UTC, choilim commented on src/content/migrate/3.mdx
> +`UglifyJsPlugin` 의 `sourceMap` 의 옵션은 `true` 대신 `false` 로 기본 설정됩니다. 즉, 최소화된 코드에 소스 맵을 사용하거나 uglifyjs 경고에 대한 올바른 줄 번호를 원하는 경우 `UglifyJsPlugin`에서 `sourceMap: true`를 설정해야 합니다.
`소스 맵` --> `소스맵` : 번역의 전반적인 부분에서 해당 띄어쓰기를 적용하고 있습니다.

2021-10-13 11:22 UTC, dlwnsgud8406 commented
> ## Summary
> #337
> 
> ## Glossary
> 영어 : 해석 CLI : CLI legacy : 레거시 uglifyjs : uglifyjs hacks : 핵 synchronously : 동기적으로 opt-out : 옵트 아웃 source maps:소스맵 naming conventions : 네이밍 컨벤션

2021-10-13 11:24 UTC, dlwnsgud8406 commented
@dkstyle @choilim  재확인 부탁드립니다 !! (_ _)

2021-10-13 12:23 UTC, dkstyle requested changes

2021-10-13 12:23 UTC, dkstyle commented on src/content/migrate/3.mdx
> +JSON 파일에 대해 설정된 로더가 없으면, webpack은 자동으로 JSON [`json-loader`](https://github.com/webpack-contrib/json-loader) 파일을 로드하려고 시도합니다.
이전 작업과 반대로 원문은 두줄인데, 한줄로 반영되었습니다.....

2021-10-13 12:23 UTC, dkstyle commented on src/content/migrate/3.mdx
> +[우리는 이것을 하기로 결정했습니다.](https://github.com/webpack/webpack/issues/3363) webpack, node.js 및 browserify 간의 환경차이를 없애기 위해서입니다.
이전 작업과 반대로 원문은 두줄인데, 한줄로 반영되었습니다.....

2021-10-13 12:23 UTC, dkstyle commented on src/content/migrate/3.mdx
> +[우리는 이것을 하기로 결정했습니다.](https://github.com/webpack/webpack/issues/3363) webpack, node.js 및 browserify 간의 환경차이를 없애기 위해서입니다.
We decided to do this in order to iron out environment differences between webpack, node.js and browserify.
[ ] 로 단어가 감싸여 있지만 연결되는 문장입니다.

----
번역규칙에 WE, YOU, SHE, HE등의 인칭대명사는 번역하지 않습니다.
따라서 `환경차이를 없애기 위해 그렇게 하기로 결정했다` 와같은 연결 표현이 되어야할 것 같습니다.

2021-10-14 00:58 UTC, dkstyle requested changes

2021-10-14 00:58 UTC, dkstyle commented on src/content/migrate/3.mdx
> +관련 옵션은 로더 문서를 참고하십시오.
원문은 한줄인데, 두줄로 반영되었습니다.

+) 참고하십시오. -> 참고하세요.

2021-10-14 00:58 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`webpack.optimize.DedupePlugin`은 더 이상 필요하지 않습니다. 설정에서 제거하십시오.
제거하십시오. -> 제거하세요.

2021-10-14 00:58 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`debug` 옵션은 webpack 1에서 로더를 디버그 모드로 전환했습니다. 이것은 장기적으로 로더 옵션을 통해 전달되어야 합니다. 관련 옵션은 로더 문서를 참고하십시오.
참고하십시오 -> 참고하세요.

2021-10-14 00:58 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`--define process.env.NODE_ENV="production"` 는 [`DefinePlugin`](/plugins/define-plugin/)를 참고하시오.
참고하시오 -> 참고하세요.

2021-10-14 04:13 UTC, dlwnsgud8406 commented
@dkstyle 조언해주셔서 감사합니다 ! 수정완료했습니다

2021-10-14 23:44 UTC, choilim commented on src/content/migrate/3.mdx
> +이전의 로더 은 로더와 그 이상의 설정이 허가되는 강력한규칙 시스템으로 대체 되었습니다.
로더 다음에 configuration이 빠진거 같습니다~

2021-10-14 23:45 UTC, choilim commented on src/content/migrate/3.mdx
> +**webpack 1** 에서, 된 로더가 일치하는 파일을 기준으로 확인되어집니다. 하지만, **webpack 2** 에서는, 설정된 로더는 `context` 옵션을 기준으로 확인됩니다.
`된 로더` --> `설정된 로더`: 설정된이 누락된거 같습니다~

2021-10-14 23:47 UTC, choilim commented on src/content/migrate/3.mdx
> +`UglifyJsPlugin` 의 `sourceMap` 의 옵션은 `true` 대신 `false` 로 기본 설정됩니다. 즉, 최소화된 코드에 소스맵을 사용하거나 uglifyjs 경고에 대한 올바른 줄 번호를 원하는 경우 `UglifyJsPlugin`에서 `sourceMap: true`를 설정해야 합니다.
``UglifyJsPlugin` 의 `sourceMap` 의 옵션은` --> ``UglifyJsPlugin` 의 `sourceMap`  옵션은`
: `sourceMap` 다음의 '의'가 문맥상 이상한거 같아요~ 위처럼 수정하면 어떨까요??

2021-10-14 23:50 UTC, choilim commented on src/content/migrate/3.mdx
> +`webpack.config.js`에서 사용자 정의 속성으로 로더를 설정할 수 _더 이상_ 없습니다. `options`을 통해 수행해야 합니다.`ts` 속성이 있는 다음 설정은 더 이상 webpack 2에서 유효하지 않습니다 :
`설정할 수 _더 이상_ 없습니다.` --> `_더 이상_ 설정할 수 없습니다.`
: 문맥상 수정되면 좋을 거 같습니다~

2021-10-15 03:14 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 플러그인의 설정 변경은 주로 구문적입니다.
구문적이다라는 표현이 생소한데요, 이해하기 쉬운 의역을 찾아보면 좋을것 같습니다.
Cc: @line/webpack-ko

2021-10-15 05:04 UTC, dlwnsgud8406 commented
@choilim @dkstyle 한번 더 확인 부탁드립니다 !

2021-10-18 01:01 UTC, choilim approved these changes

2021-10-18 02:05 UTC, YukJiSoo requested changes

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +위 3개의 파일들 `resolve.modules`하나로 대체되었습니다. 자세한 사용법은 [resolving](/configuration/resolve)을 참고하세요.
위 3개의 파일들 `resolve.modules`하나로 대체되었습니다.
-> 위 3개의 옵션들은 `resolve.modules`로 대체되었습니다.

파일보다는 옵션으로 번역되는게 맞는것 같습니다!

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +T> webpack 2와 3 사이에 변경 사항이 훨씬 적으므로 이주가 그렇게 나쁘지 않을 것입니다. 문제가 발생하는 경우, 자세한 내용은 [the changelog](https://github.com/webpack/webpack/releases)를 참고하세요.
이주라는 표현이 어색하므로 마이그레이션으로 바꾸는것이 어떨까요??

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +이전의 로더구성 은 로더와 그 이상의 설정이 허가되는 강력한규칙 시스템으로 대체 되었습니다.
로더구성 은 -> 로더 설정은
강력한규칙 -> 강력한 규칙

띄어쓰기와 번역된 단어가 어색합니다!

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +JSON 파일에 대해 설정된 로더가 없으면, webpack은 자동으로 JSON [`json-loader`](https://github.com/webpack-contrib/json-loader) 파일을 로드하려고 시도합니다.
webpack은 자동으로 JSON `json-loader` 파일을 로드하려고 시도합니다.
-> webpack은 자동으로 `json-loader`로 JSON 파일을 로드하려고 시도합니다.

문장 구조를 바꾸는게 조금 더 읽기 자연스러워질 것 같아요!

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +[환경차이를 없애기 위해 그렇게 하기로 결정했습니다.](https://github.com/webpack/webpack/issues/3363) webpack, node.js 및 browserify 간의 환경차이를 없애기 위해서입니다.
같은 내용이 반복되는 것 같아서 링크가 걸린 문장을 뒤로 보내도 될 것 같아요!
```
webpack, node.js 및 browserify 간의 환경차이를 없애기 위해서 [결정을 내렸습니다.](https://github.com/webpack/webpack/issues/3363)
```

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +`webpack.config.js`에서 사용자 정의 속성으로 로더를 _더 이상_ 설정할 수없습니다. `options`을 통해 수행해야 합니다.`ts` 속성이 있는 다음 설정은 더 이상 webpack 2에서 유효하지 않습니다 :
합니다.`ts` -> 합니다. `ts`

띄어쓰기를 추가해주세요!

2021-10-18 02:05 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +webpack 1에서는 [`require.ensure()`](/api/module-methods/#requireensure) 를 응용 프로그램의 를 지연 로드하는 방법으로 사용할 수 있습니다 :
응용 프로그램의 를 지연 로드하는 방법으로 사용할 수 있습니다 :
-> 응용 프로그램에서 청크를 지연 로드하는 방법으로 사용할 수 있습니다.

2021-10-18 02:10 UTC, YukJiSoo commented
`:`로 끝마치는 문장이 많습니다. 번역 가이드에 맞게 마침표로 수정해주세요!
https://github.com/line/webpack.kr/blob/kr/CONTRIBUTING_UNIVERSAL.md

2021-10-18 02:15 UTC, dkstyle commented on src/content/migrate/3.mdx
> +위 3개의 파일들 `resolve.modules`하나로 대체되었습니다. 자세한 사용법은 [resolving](/configuration/resolve)을 참고하세요.
3개의 파일이라는 표현은 원문에 없습니다.

2021-10-18 07:29 UTC, keipark commented on src/content/migrate/3.mdx
> +좋은 질문입니다. 음, 엄밀히 말하면 2가지 가능성이 있습니다. webpack 로더를 설정하는 두 가지 방법. 고전적으로 `options`은 `query`라고 했으며 로더 이름에 추가할 수 있는 문자열이었습니다. 쿼리 문자열과 매우 유사하지만 실제로는 [더 강력한 기능](https://github.com/webpack/loader-utils#parsequ
이부분은 조금 더 자연스럽게 읽히도록 의역해보면 좋을 것 같습니다~
well, hmm 등 영어 구문 표현은 한글에서는 어색한 경우가 있어 꼭 번역에 포함되지 않아도 괜찮습니다.

```
예: 좋은 질문입니다. 엄밀히 말하면 2가지로 해석 가능하며, 모두 webpack 로더를 설정하는 방법입니다. ...`
```

2021-10-18 07:29 UTC, keipark commented on src/content/migrate/3.mdx
> +`--define process.env.NODE_ENV="production"` 는 [`DefinePlugin`](/plugins/define-plugin/)를 참고하세요.
조사는 앞 단어에 붙여서 작성되어야 합니다. 
그리고 소리내어 읽었을때 자연스럽게 읽히는 조사를 사용해주세요. 

예: `--define ... production은`

2021-10-28 04:30 UTC, dlwnsgud8406 commented
@keipark  @YukJiSoo  재검토 부탁드립니다 ~

2021-10-28 12:23 UTC, dkstyle commented on src/content/migrate/3.mdx
> +위 3개의 옵션들은 `resolve.modules`로 대체되었습니다. 자세한 사용법은 [resolving](/configuration/resolve)을 참고하세요.
원문에 3개라는 표현이 없는데, 3개라고 표현할 필요가 있을까요?

2021-10-28 12:29 UTC, dkstyle commented on src/content/migrate/3.mdx
> +`--define process.env.NODE_ENV="production"`는 [`DefinePlugin`](/plugins/define-plugin/)를 참고하세요.
소리내어 읽었을 때 자연스럽게 읽히는 조사를 사용해주세요.

예: --define ... production은

2021-10-28 12:38 UTC, dkstyle commented on src/content/migrate/3.mdx
> +좋은 질문입니다. 엄밀히 말하면 2가지 가능성이 있습니다. 모두 webpack 로더를 설정하는 방법입니다. 고전적으로 `options`은 `query`라고 했으며 로더 이름에 추가할 수 있는 문자열이었습니다. 쿼리 문자열과 매우 유사하지만 실제로는 [더 강력한 기능](https://github.com/webpack/loader-utils#parsequer
앞서 다른분께서도 제안드렸던 방법인데요.

```
Well, strictly speaking it's 2 possible things; both ways to configure a webpack loader.
```
원문에서도 구두점으로 나뉘어진 문장이 아니기 때문에, 이어진 문장으로의 표현이 더 자연스럽지 않을까 싶습니다.

```
예: 좋은 질문입니다. 엄밀히 말하면 2가지로 해석 가능하며, 모두 webpack 로더를 설정하는 방법입니다. ...`

혹은

예: 엄밀히 말하면 webpack 로더를 설정하는 두 가지 방법 모두 가능합니다.
```

2021-10-30 05:03 UTC, dlwnsgud8406 commented on src/content/migrate/3.mdx
> +좋은 질문입니다. 엄밀히 말하면 2가지 가능성이 있습니다. 모두 webpack 로더를 설정하는 방법입니다. 고전적으로 `options`은 `query`라고 했으며 로더 이름에 추가할 수 있는 문자열이었습니다. 쿼리 문자열과 매우 유사하지만 실제로는 [더 강력한 기능](https://github.com/webpack/loader-utils#parsequer
넵 수정확인 부탁드립니다 !

2021-10-30 07:28 UTC, YukJiSoo commented on src/content/migrate/3.mdx
> +`webpack.config.js`에서 사용자 정의 속성으로 로더를 _더 이상_ 설정할 수없습니다. `options`을 통해 수행해야 합니다. `ts` 속성이 있는 다음 설정은 더 이상 webpack 2에서 유효하지 않습니다 :
: 을 . 으로 바꿔주세요!

2021-10-30 07:30 UTC, dlwnsgud8406 commented on src/content/migrate/3.mdx
> +`webpack.config.js`에서 사용자 정의 속성으로 로더를 _더 이상_ 설정할 수없습니다. `options`을 통해 수행해야 합니다. `ts` 속성이 있는 다음 설정은 더 이상 webpack 2에서 유효하지 않습니다 :
넵 !

2021-10-30 07:31 UTC, YukJiSoo approved these changes
고생하셨습니다!

2021-10-30 13:53 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 옵션은 더 이상 빈 문자열을 전달할 필요가 없습니다. 이 동작은 `resolve.enforceExtension`로 이동되었습니다. 자세한 사용법은 [resolving](/configuration/resolve) 를 참고하세요.
`resolve.enforceExtension`로 -> `resolve.enforceExtension`으로

2021-10-30 13:55 UTC, dlwnsgud8406 commented on src/content/migrate/3.mdx
> +이 옵션은 더 이상 빈 문자열을 전달할 필요가 없습니다. 이 동작은 `resolve.enforceExtension`로 이동되었습니다. 자세한 사용법은 [resolving](/configuration/resolve) 를 참고하세요.
넵 수정했습니다 !

2021-10-30 15:12 UTC, dkstyle commented
@dlwnsgud8406 위에 커멘트 드린 내용도 한번씩만 더 확인 부탁드립니다.

2021-10-30 15:20 UTC, dkstyle commented on src/content/migrate/3.mdx
> +이 옵션은 더 이상 빈 문자열을 전달할 필요가 없습니다. 이 동작은 `resolve.enforceExtension`로 이동되었습니다. 자세한 사용법은 [resolving](/configuration/resolve) 를 참고하세요.
커밋 내용에 수정사항이 반영되지 않았습니다.

2021-11-01 01:53 UTC, keipark commented on src/content/migrate/3.mdx
> +`--define process.env.NODE_ENV="production"` 는 [`DefinePlugin`](/plugins/define-plugin/)를 참고하세요.
아래에도 코멘트 주셨지만 제대로 반영이 되지 않은 것 같아요~ 다시한번 확인부탁드립니다.

2021-11-01 04:34 UTC, dlwnsgud8406 commented
> @dlwnsgud8406 위에� 이전에 커멘트 드린 내용도 한번씩만 더 확인 부탁드립니다.

네넵

2021-11-01 12:02 UTC, dlwnsgud8406 commented on src/content/migrate/3.mdx
> +위 3개의 옵션들은 `resolve.modules`로 대체되었습니다. 자세한 사용법은 [resolving](/configuration/resolve)을 참고하세요.
네넵 수정했습니다

2021-11-01 12:48 UTC, dkstyle approved these changes
수고하셨습니다!

2021-11-02 00:20 UTC, dlwnsgud8406 commented
@dkstyle 고생하셨습니다 !

2021-11-02 00:44 UTC, merged