Translate migrate/5.mdx
line/webpack.kr pull request #340
Opened 2021-10-11 14:15 UTC by Maphnew

## Summary 

[#7 ](https://github.com/line/webpack.kr/issues/7)

## Glossary

primitive value: 원시 값
validation error: 유효성 검사 오류

2021-10-13 05:00 UTC, choilim commented on src/content/migrate/5.mdx
> +이 가이드는 webpack을 직접 사용할 때 webpack 5로 마이그레이션 하는 데 도움이 되는 것을 목표로 합니다. webpack을 실행하기 위해 더 높은 수준의 도구를 사용하는 경우 그 도구의 마이그레이션 지침을 참조하세요.
`참조하세요` --> `참고하세요` : 이런 문맥의 대부분의 경우는 `참고하세요`를 지향하고 있습니다~

2021-10-13 05:00 UTC, choilim commented on src/content/migrate/5.mdx
> +   - webpack 버전 4 미만을 사용하는 경우 [webpack 4 마이그레이션 가이드](https://webpack.kr/migrate/4/)를 참조하세요.
참조 --> 참고

2021-10-13 05:03 UTC, choilim commented on src/content/migrate/5.mdx
> +- `target`이 함수로 설정되어 있으면 `false`로 업데이트하고 `plugins` option 내에서 해당 함수를 적용하세요. 아래 예를 참조하세요.
참조 --> 참고

2021-10-13 05:04 UTC, choilim commented on src/content/migrate/5.mdx
> +- `output.path: path.resolve(__dirname, 'dist')`는 생략해도 됩니다. 기본값입니다.
`you can omit it`은 위와 동일한 문장인데, `는 생략할 수 있습니다.` `는 생략해도 됩니다. `두가지 번역으로 나뉘고 있는거 같습니다~

2021-10-14 00:48 UTC, dkstyle commented
문서에 들어간 전체 링크에 https://webpack.kr/ 를 붙여 주셨는데요, 문서가 보여지는 도메인 하위로 이동하기때문에, 원문 그대로 유지해주셔도 될 것 같습니다.

2021-10-14 00:49 UTC, dkstyle requested changes

2021-10-14 00:49 UTC, dkstyle commented on src/content/migrate/5.mdx
> +- `Optimization.splitChunks.cacheGroups: { default: false, vendors: false }`를 설정하여 기본값을 끌(turn off) 수 있었습니다. 우리는 이것을 권장하지 않지만, webpack 5에서 같은 효과를 얻고 싶다면 `optimization.splitChunks.cacheGroups: { defau
WE, YOU, SHE, HE등의 인칭대명사는 번역하지 않습니다.

2021-10-14 00:54 UTC, dkstyle requested changes

2021-10-14 00:54 UTC, dkstyle commented on src/content/migrate/5.mdx
> +빌드 errors/warnings를 주의 깊게 읽으십시오. 해당하는 조언이 없는 경우 issue를 생성해 주시면 해결해 드리겠습니다.
문체의 일관성을 위해 읽으십시오. -> 읽어보세요. 와같은 표현으로 되면 좋을것습니다.

2021-10-14 00:54 UTC, dkstyle commented on src/content/migrate/5.mdx
> +      - 어떤 경우에는 더 나은 스택 추적을 위해 `--no-turbo-inlining` 플래그를 사용해 보십시오.
보십시오.->  보세요.

2021-10-14 00:54 UTC, dkstyle commented on src/content/migrate/5.mdx
> +[issue](https://github.com/webpack/webpack/issues/new?template=Bug_report.md)를 만들고 마이그레이션 중에 발생한 문제에 대해 알려주십시오.
알려주십시오. -> 알려주세요.

2021-10-14 00:54 UTC, dkstyle commented on src/content/migrate/5.mdx
> +    - `process.env.VARIABLE`과 함께 환경 변수를 사용하고 싶으십니까? 설정에서 이러한 변수를 정의하려면 `DefinePlugin` 또는 `EnvironmentPlugin`을 사용해야 합니다.
싶으십니까? -> `싶으신가요?`, `싶으세요?` 정도로 변경하면 더 자연스러울 것 같은데, 어떨까요?

2021-10-14 01:00 UTC, dkstyle commented on src/content/migrate/5.mdx
> +#### `/* webpackChunkName: '...' */` 사용
소제목은 원문추적과 링크생성을 위해 번역하지 않습니다.

2021-10-14 23:54 UTC, choilim commented on src/content/migrate/5.mdx
> +`webpack`, `webpack-cli`, 플러그인 그리고 로더를 업그레이드하면서 새로운 error와 warning이 있을 수 있습니다. 빌드 중 사용 중단 경고를 주시하세요.
error: 오류
warning: 경고
: 파일에서 전반적으로 위처럼 번역하고 있는거 같습니다~ 여기도 번역해주세요!

2021-10-15 03:16 UTC, dkstyle approved these changes

2021-10-18 01:01 UTC, choilim approved these changes

2021-10-18 02:20 UTC, YukJiSoo commented on src/content/migrate/5.mdx
> +- `Optimization.splitChunks.cacheGroups: { default: false, vendors: false }`를 설정하여 기본값을 끌(turn off) 수 있었습니다. 이것을 권장하지 않지만, webpack 5에서 같은 효과를 얻고 싶다면 `optimization.splitChunks.cacheGroups: { default:
(turn off) 를 제거해줘도 문장을 이해하는데 문제가 없을 것 같다고 생각합니다!

2021-10-18 02:20 UTC, YukJiSoo commented on src/content/migrate/5.mdx
> +  확실히 할 것들:
문장 끝의 : 를 마침표로 바꿔주세요!

2021-10-18 02:20 UTC, YukJiSoo commented on src/content/migrate/5.mdx
> +  사용 중단 경고를 많을 수 있습니다. 이것은 직접적인 문제가 아닙니다. 플러그인은 핵심 변경 사항을 따라잡을 시간이 필요합니다. 이러한 지원 중단을 플러그인에 보고하세요. 이러한 지원 중단은 경고일 뿐이며 빌드는 여전히 약간의 단점(예: 성능 저하)으로만 작동합니다.
경고를 ->  경고가

2021-10-18 02:20 UTC, YukJiSoo commented on src/content/migrate/5.mdx
> +    - `--profile` `--progress`는 이제 간단한 성능 프로필을 표시합니다.
원문을 유지해주세요!

`--profile` `--progress` -> `--profile --progress`

2021-10-18 02:20 UTC, YukJiSoo commented on src/content/migrate/5.mdx
> +  - 증분 빌드에서 모듈을 빌드하는 시간은 webpack 4에서와같이 안전하지 않은 캐싱으로 되돌리면 개선될 수 있습니다.
4에서와같이 -> 4에서와 같이

2021-10-18 09:45 UTC, keipark commented on src/content/migrate/5.mdx
> +- Node.js의 경우 빌드에는 `target` option에 지원되는 Node.js 버전이 포함되며 webpack은 지원되는 구문을 자동으로 파악합니다. 예를 들어`target: 'node8.6'`.
마지막 `예를 들어~` 부분을 문장에 포함하거나 괄호 처리하는것이 더 자연스러울 것 같습니다. 
```
(예: `target: 'node8.6'`)

예를 들어 `target: 'node8.6'`와 같이 사용합니다. 
```

2021-10-18 09:45 UTC, keipark commented on src/content/migrate/5.mdx
> +- Webpack 5는 `webpackChunkName`을 사용하지 않는 경우에도 `development` mode에서 유용한 파일 이름을 자동으로 할당합니다.
mode = 모드로 통일해주세요~

2021-10-20 03:44 UTC, YukJiSoo approved these changes

2021-10-20 07:46 UTC, merged