Translate blog/2020-12-08-roadmap-2021.mdx
line/webpack.kr pull request #345
Opened 2021-10-13 11:39 UTC by syw2045

Translate blog/2020-12-08-roadmap-2021.mdx

## Glossary
side-effect-free :  side-effect-free
optimizer : 옵티마이저
web worker : 웹 워커
wrapping : wrapping 
edge case : 엣지 케이스

2021-10-13 11:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/line/webpack.kr?pullRequest=345) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/line/webpack.kr?pullRequest=345) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/line/webpack.kr?pullRequest=345) it.</sub>

2021-10-14 00:24 UTC, dkstyle requested changes
translator 항목에 불필요한 공백이 들어가서 마크다운 문서가 깨졌습니다.
번역 이후 원문의 문서 변경사항 추적을 위해 가능하면 원문의 라인을 그대로 유지한채로 번역을 진행해 주세요.
또한 한글 문서의 가독성을 위한 불가피한 경우가 아니라면 공백라인은 추가하지 않아야합니다.

번역 완료된 원문은 제거되어야합니다.

번역기여방법 문서를 다시 참고해주세요.

2021-10-14 00:26 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +우리는 많은 webpack 사용자가 빌드를 위해 사용자 정의 항목을 필요로 하고 구성 가능성과 풍부한 플러그인 시스템을 통해 웹팩이 제공하는 것이라고 생각합니다.
webpack은 webpack으로 통일해주세요.

2021-10-14 00:27 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +우리는 많은 webpack 사용자가 빌드를 위해 사용자 정의 항목을 필요로 하고 구성 가능성과 풍부한 플러그인 시스템을 통해 웹팩이 제공하는 것이라고 생각합니다.
WE, YOU, SHE, HE등의 인칭대명사는 번역하지 않습니다.

2021-10-18 02:11 UTC, dkstyle commented
@syw2045 원문의 형식을 유지하지 않고 업데이트하셔서 작업해주신 내용이 제대로 번역되었는지 확인하기가 어렵습니다.
다른분들의 작업을 참고하여 다시 올려주세요.

2021-11-01 01:44 UTC, dkstyle commented
@syw2045 translator 부분 규격을 규칙에 맞게 작성해 주세요. 
현재 작성위치와 줄바꿈 규칙이 문서규격과 맞지 않습니다.

2021-11-01 12:51 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +translators:
translators 항목의 위치는 contributors 아래에 있어야 정상적으로 반영됩니다.
PR올리신 다른 분들의 작업내용을 참고하여 수정해주세요.

2021-11-04 05:54 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> -
원문의 공백 라인도 유지를 부탁드립니다.

2021-11-04 05:55 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +이러한 경우에 대한 경고를 표시하고자 합니다.
이 내용은 번역이 잘못 들어간것으로 보입니다.

2021-11-04 05:57 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +주요 이점은 개발자 경험입니다. `mini-css-extract-plugin` 구성은 가장 쉬운 일이 아니며 이를 제거하면 개발자가 많이 단순화할 수 있습니다.
이 부분부터 다시 원문과 라인 싱크가 맞지 않습니다.

2021-11-04 05:58 UTC, dkstyle commented
실수로 작업과 무관한 ```src/content/blog/2020-10-10-webpack-5-release.mdx ``` 파일을 삭제하신것으로 보입니다.

2021-11-04 13:17 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +웹 webpack을 대상으로 할 때 `script` 태그를 통해 청크를 로드합니다.
```When targeting the web, webpack loads chunks via `script` tags.``` 
```웹을 대상으로 할 때, webpack은 `script` 태그를 통해 청크를 로드합니다. ```와 같은 의미로 쓰인 내용이 아닐까 싶네요.
아래 다른 부분의 내용도 마찬가지로 보입니다.

2021-11-09 00:37 UTC, choilim commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +- `production`모드의 webpack 5 최적화는 각 런타임(종종 진입점과 동일함)에 대해 사용된 exports 분석 (Tree Shaking)을 실행하므로 webpack이 각 런타임(해당 진입점)을 개별적으로 최적화할 수 있습니다.
진입점의 경우는 엔트리 포인트로 반영 부탁드립니다~(glossary 참고)

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +webpack은 타이핑 측면과 런타임측면에서 몇가지를 더 선보였습니다. 몇 가지의 낮은 처리 성능이 향상되었습니다. 어떤 경우들에서 유효하지 않고/부정확함을 발생시키는 세미콜론이 없는 코드는 수정되었습니다. 부작용이 없는 코드 + 연결된 모듈 + 재배포의 조합으로 일부 극단적인 경우가 발생했으며 이 경우는 수정되었습니다(적어도 알려진 경우).
전체적으로 webpack이 문장 처음에 올때는 대문자를 사용하여 `Webpack`으로 작성해주세요.

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +하지만 사용자가 보고한 한 가지 버그로 인해 완전히 새로운 내부 기능이 필요하게 되었습니다. webpack 내부가 지루하거나 너무 복잡하다고 생각되면 건너뛰고 다음 쳅터로 넘어갈 수 있습니다.
외래어 표기를 맞춰주세요 :)
* 쳅터 > 챕터

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +이는 앞서 언급한 극단적 상황의 다른 엔트리 포인트에 대해 런타임에 사용할 수 없는 side-effect-free 모듈을 참조하는 코드를 생산한다는 것을 의미하며, 이는 `undefined is not a function` 또는 `cannot read property `call` of undefined`로 이어집니다.
`call`에는  원문처럼 백틱 대신 '' 작은 따옴표를 사용해주세요~

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +그러나 edge case를 처리하는 것은 webpack의 강점 중 하나이므로(유지 해야하고) 이러한 문제를 해결하기 위해 계속 노력하고 싶습니다.
* 문서내에서 edge case에 대한 번역을 맞추면 좋을 것 같습니다~
* 보통 `엣지 케이스`라고도 하는데 확인 부탁드립니다. :)
* `(유지 해야하고)` 이부분은 풀어서 `webpack의 강점 중 하나를 유지하는 것이므로...` 와 같이 작성하면 어떠신가요?

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +`import()` (`type: "import"`)도 외부 로드에 사용할 수 있지만 'import'(`type: "module"`)는 아직 사용할 수 없습니다
마침표가 빠져있습니다~

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +`import`의 절대적인 URL은 의미가 있다. 예를 들어 API를 ESM으로 제공하는 외부서비스를 사용할 때: `import { event } from "https://analytics.company.com/api/v1.js"` (`import("https://analytics.company.com/api/v1.js")` 이 외부 서비스에 의존할 때
여기서는 초반 문장을 합쳐주면 조금 더 자연스러울 것 같은데 어떠신가요?
```
// 예:
`import`의 절대적 URL은 API를 ESM으로 제공하는 외부서비스를 사용할 때 의미가 있습니다.  `import...` 이 외부 서비스에 의존할 때...
```

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +Node.js의 자바스크립트 실행은 기본적으로 단일 스레드이지만 최근 추가되면서 WebWorkers와 유사한 API인 'worker_threads'를 사용할 수 있습니다.
* workder_threads > 원문의 백틱을 유지해주세요

2021-11-10 07:27 UTC, keipark commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +따라서 기술적으로 바닐라 웹 앱은 webpack과 함께 즉시 작동해야 하지만 이동 중에도 최적화됩니다.
* on the go = `작동과 함께` 라는 의미에 가까운 것 같습니다~ 
```
// 예:
...작동해야 합니다. 하지만 이와 함께 최적화도 되어야 합니다. 
```

2021-11-11 04:53 UTC, keipark approved these changes

2021-11-11 06:06 UTC, dkstyle commented
@syw2045 PR작성 시기가 오래되어, kr 브랜치의 최신 내용 재반영이 필요해 보입니다.
```src/content/blog/2020-10-10-webpack-5-release.mdx``` 파일은 작업 PR과 상관 없는 내용이므로, 변경사항이 나타나지 않도록 해주세요.

2021-11-11 08:19 UTC, syw2045 commented
> @syw2045 PR작성 시기가 오래되어, kr 브랜치의 최신 내용 재반영이 필요해 보입니다. `src/content/blog/2020-10-10-webpack-5-release.mdx` 파일은 작업 PR과 상관 없는 내용이므로, 변경사항이 나타나지 않도록 해주세요.

2021-11-11 08:21 UTC, syw2045 commented
죄송한데 `src/content/blog/2020-10-10-webpack-5-release.mdx` 파일을 안보이게하려면 `Files changed`에서 `delete file` 하면될까요...?

2021-11-12 02:06 UTC, dkstyle requested changes

2021-11-12 02:06 UTC, dkstyle commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +현재로서는 이것이 가치가 있는지 확실하지 않다. 하지만 적어도 조사할 가치가 있습니다.
경어체를 사용해 주세요.

2021-11-12 02:08 UTC, dkstyle commented
@syw2045 PR에 잘못올라간 파일을 제거하는 방법에 대한 문서를 참고하세요.
https://ffeathers.wordpress.com/2020/03/21/removing-an-updated-file-from-a-pr-on-github/#:~:text=If%20the%20unwanted%20updates%20are,the%20file%20from%20the%20PR.

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +Webpack은 타이핑 측면과 런타임측면에서 몇가지를 더 선보였습니다. 몇 가지의 낮은 처리 성능이 향상되었습니다. 어떤 경우들에서 유효하지 않고/부정확함을 발생시키는 세미콜론이 없는 코드는 수정되었습니다. 부작용이 없는 코드 + 연결된 모듈 + 재배포의 조합으로 일부 극단적인 경우가 발생했으며 이 경우는 수정되었습니다(적어도 알려진 경우).
유효하지 않고/부정확함을 -> 유효하지 않고 부정확함을

/  구분자가 필요없어 보입니다!

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +따라서 후원 상황을 정리 할 수 있다고 가정하면 2021년에는 다음이 계획됩니다.
> 다음이 계획됩니다.

해당 부분을 더 자연스럽게 읽히도록 번역하는 것은 어떨까요??

```
ex) 아래의 일들이 계획되어있습니다.
```

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +ESM exports 및 import 지원될 때 사람들은 라이브러리 번들링이 의미가 있다고 생각할 수 있으며 일부 경우에는 사실일 수도 있지만 대부분의 경우 기본적으로 번들링은 더 나쁜 결과를 초래할 것입니다.
import 지원될 때 -> import가 지원될 때

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +[State of CSS 2020](https://2020.stateofcss.com/en-US/technologies/css-in-js/) 현재 CSS 모듈은 모듈식 CSS를 작성하는 인기 있는 방법이며 기본 모듈 유형입니다. webpack을 사용하면 Tree Shaking(Used Exports Optimization 및 Side-Effects 최적화
State of CSS 2020 현재 CSS 모듈은 -> State of CSS에 따르면 2020 현재 CSS

State of CSS 2020 뒷부분의 내용과 자연스럽게 이어지면 좋을 것 같습니다!

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +Webpack과 함께 (전체) SourceMaps를 사용하는 것은 현재 Webpack에서 상당히 비쌉니다. SourceMap 처리 성능이 최고가 아니기 때문입니다.
SourceMaps를 -> SourceMaps을

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +Node.js 14는 패키지의 엔트리 포인트를 정의할 수 있도록 package.json의 'exports' 필드에 대한 지원을 추가했습니다.
'exports' -> `exports`
작은 따옴표를 백틱으로 변경해주세요!

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +Webpack 5는 이를 따랐고 '생산/개발'과 같은 추가 조건을 추가했습니다.
'생산/개발' -> `production/development`
- 작은 따옴표를 백틱으로 변경해주세요!
- 특정한 조건을 가리키기 때문에 번역하지 않고 원문 그대로 표기하는 것이 더 나을 것 같습니다!

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +그 직후 Node.js는 이에 대한 추가 기능을 추가했습니다. 그들은 또한 개인 수입을 위한 '가져오기' 필드를 추가했습니다.
'가져오기'
- 작은 따옴표를 백틱으로 변경해주세요!
- 특정한 조건을 가리키기 때문에 번역하지 않고 원문 그대로 표기하는 것이 더 나을 것 같습니다!

2021-11-15 05:09 UTC, YukJiSoo commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +그것은 추가하고 싶은 것입니다.
더 자연스럽게 번역하는 것은 어떨까요?
```
ex) 우리가 추가하고 싶은 것중 하나입니다.
```

2021-11-16 10:03 UTC, dkstyle commented
수정사항은 잘 정리해주신것 같습니다.
upstream(line:kr)의 최신 내용을 현재 작업하고 계시는 branch(syw2045:ssong)에 업데이트 반영해서 한번 더 올려주시겠어요?

![image](https://user-images.githubusercontent.com/749881/141964564-6cd309b1-878f-4f82-b52c-cc719f5b3a8c.png)

2021-11-17 04:52 UTC, dkstyle approved these changes

2021-11-17 13:37 UTC, choilim approved these changes

2021-11-17 13:37 UTC, choilim commented on src/content/blog/2020-12-08-roadmap-2021.mdx
> +- `production`모드의 webpack 5 최적화는 각 런타임(종종 진입점과 동일함)에 대해 사용된 exports 분석 (Tree Shaking)을 실행하므로 webpack이 각 런타임(해당 진입점)을 개별적으로 최적화할 수 있습니다.
다른 쪽에서 사용된 `entrypoints`의 경우도 확인 부탁드려요!

2021-11-19 06:13 UTC, YukJiSoo approved these changes

2021-11-19 06:15 UTC, merged