Translate contribute/writers-guide.mdx
line/webpack.kr pull request #346
Opened 2021-10-13 12:04 UTC by angrymusic

## Summary 

#336

## Glossary

// 영어단어: 번역
article: 글
camel-case: camel-case
kebab-case: kebab-case
Further Reading: 추가 읽기
backticks: 백틱
section: 섹션
paragraph: 문단

2021-10-14 00:41 UTC, dkstyle requested changes

2021-10-14 00:41 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +1. 간략한 소개 - 어떤 것을 왜 하였는지에 대한 아이디어를 적은 한두 문장.
sentence가 문장이고 paragraph는 문단입니다.

2021-10-14 00:41 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> + - [github username]
불필요한 공백조정 변경이 반영되었습니다.

2021-10-14 00:41 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> + - title: Title of Related Article
불필요한 공백조정 변경이 반영되었습니다.

2021-10-14 00:41 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +- `title`: 이 글의 제목입니다.
일반적인 작성가이드에 대한 설명이기때문에, `이 글의`이라는 표현이 들어가면 writers-guide를 의미하는 것이 될 수 있기 때문에 의미가 다르게 전달될 수 있어 보입니다.

2021-10-14 00:41 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +`related`는 페이지 하단에 **추가 읽기** 섹션을 생성하고 `contributors`는 그 아래에 **Contributors** 섹션을 생성합니다. 글을 편집하고 인정받고 싶다면 주저하지 말고 GitHub 사용자 이름을 'contributors' 목록에 추가하세요.
한글 문서에서 소제목은 원문 그대로 두기 때문에, 문서의 Further Reading 항목도 그대로 유지됩니다. 
따라서 Further Reading은 원문 그대로 쓰시는게 좋을 것 같습니다.

2021-10-14 00:41 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> -And in inline backticks:
인라인 백틱안에서의 내용을 설명하는 내용인것 같습니다.

2021-10-14 01:03 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +2. 남은 콘텐츠 개요 – 콘텐츠가 표시되는 방식.
다른 내용과 표현의 일관성을 위해 방식 -> 방식입니다. 와같이 표현하는것이 좋을 것 같습니다.

2021-10-14 02:12 UTC, choilim commented on src/content/contribute/writers-guide.mdx
> +'array'에 여러 유형이 허용되는 경우 쉼표를 사용합니다.
` 가 ' 로 수정된 것 같습니다~

2021-10-14 02:16 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +2. '편집'을 누르고 구조를 확장하세요.
'편집' -> `편집` 
' -> `

2021-10-14 04:32 UTC, choilim commented on src/content/contribute/writers-guide.mdx
> +숫자를 표시하려면 'number'를 사용하세요.
` 가 ' 로 수정된 것 같습니다~

2021-10-14 04:45 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +`object = { string }`
원문 내용을 수정하신 이유가 있을까요?

2021-10-14 05:12 UTC, choilim commented on src/content/contribute/writers-guide.mdx
> +| --devtool  | 번들 리소스에 대한 소스 맵 유형 정의 | string     | -             |
띄어쓰기: `소스 맵` --> `소스맵` : 띄어쓰지 않는 것이 해당 번역 프로젝트의 규칙입니다~

2021-10-14 05:15 UTC, choilim commented on src/content/contribute/writers-guide.mdx
> +예제는 [EvalSourceMapDevToolPlugin' page의 `options` 섹션](/plugins/eval-source-map-dev-tool-plugin/#options)에서 찾을 수 있습니다.
' 다음에 s가 빠진 것 같습니다~

2021-10-16 04:26 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +1. 간략한 소개 - 어떤 것을 왜 하였는지에 대한 아이디어를 적은 한두 문장.
감사합니다! 수정완료했습니다^^

2021-10-16 04:26 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +- `title`: 이 글의 제목입니다.
감사합니다! 수정완료했습니다^^

2021-10-16 04:26 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +`related`는 페이지 하단에 **추가 읽기** 섹션을 생성하고 `contributors`는 그 아래에 **Contributors** 섹션을 생성합니다. 글을 편집하고 인정받고 싶다면 주저하지 말고 GitHub 사용자 이름을 'contributors' 목록에 추가하세요.
감사합니다! 수정완료했습니다^^

2021-10-16 04:27 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> -And in inline backticks:
감사합니다! 수정완료했습니다^^

2021-10-16 04:27 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +'array'에 여러 유형이 허용되는 경우 쉼표를 사용합니다.
감사합니다! 수정완료했습니다^^

2021-10-16 04:28 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +`object = { string }`
실수로 빼먹은 것 같네요! 죄송합니다 ㅎㅎ;;

2021-10-18 02:18 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> + - [github username]
수정해주세요.

2021-10-18 02:18 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> + - title: Title of Related Article
수정해주세요.

2021-10-18 02:29 UTC, YukJiSoo requested changes

2021-10-18 02:29 UTC, YukJiSoo commented on src/content/contribute/writers-guide.mdx
> +3. 변경 점들을 Pull Request에 생성하세요.
변경 점 -> 변경점

2021-10-18 02:29 UTC, YukJiSoo commented on src/content/contribute/writers-guide.mdx
> +`related`는 페이지 하단에 **Further Reading** 섹션을 생성하고 `contributors`는 그 아래에 **Contributors** 섹션을 생성합니다. 글을 편집하고 인정받고 싶다면 주저하지 말고 GitHub 사용자 이름을 'contributors' 목록에 추가하세요.
'contributors' -> \`contributors\`

작은 따옴표를 백틱으로 바꿔주세요!

2021-10-18 02:29 UTC, YukJiSoo commented on src/content/contribute/writers-guide.mdx
> +- 로더는 역 따옴표로 묶여 있으며 [kebab-cased](https://en.wikipedia.org/w/index.php?title=Kebab_case): `css-loader`, `ts-loader`, …
문장을 마무리하면 더 자연스러울 것 같습니다.

ex) kebab-cased 입니다.

2021-10-18 02:29 UTC, YukJiSoo commented on src/content/contribute/writers-guide.mdx
> +플러그인을 사용 가능한 옵션 값 유형으로 표시하려면 'Plugin'의 camel-cased 형식의 제목을 사용하세요.
'Plugin'
원문과 동일하게 작은 따옴표 대신 백틱으로 바꿔주세요!

2021-10-18 02:29 UTC, YukJiSoo commented on src/content/contribute/writers-guide.mdx
> +객체의 키가 동적이며 사용자 정의된 경우 ``를 사용하여 설명합니다.
<key> 가 누락되었습니다!

2021-10-18 06:06 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +- `sort`: 해당 섹션 (또는) 하위 섹션 내에서 이 글의 순서입니다.
이전 수정 요청과 마찬가지로 `이 글의` 에서 `이`가 빠져야 자연스러울 것 같습니다. 
아래 contributors 항목도 동일

2021-10-18 08:52 UTC, keipark commented on src/content/contribute/writers-guide.mdx
>  + As we've learned in [production guide](/guides/production/)...
윗 문장을 이해할 수 있도록 diff도 번역해주시면 좋을 것 같아요~

2021-10-18 08:52 UTC, keipark commented on src/content/contribute/writers-guide.mdx
> +모든 것에 단순하다고 가정하지 마세요. 'just', 'simply'와 같은 단어를 피하세요.
* 모든 것에 > `모든 것이`
* just, simply > `그냥`, `간단하게` 같이 번역해도 좋을 것 같습니다.

2021-10-18 08:52 UTC, keipark commented on src/content/contribute/writers-guide.mdx
>  - Simply run command...
여기 diff도 확인해주세요 :)

2021-10-18 08:52 UTC, keipark commented on src/content/contribute/writers-guide.mdx
> +문서를 액세스할 수 있고 잘 작성할 수 있도록 항상 모든 문서 옵션에 유형과 기본값을 제공하세요. 저희는 문서화된 옵션에 권한을 부여한 후 유형과 기본값을 추가합니다.
* accessible = `쉽게 이해 가능한`의 뜻이 더 강해 보입니다. 조금 의역이 들어가면 좋을 것 같습니다.
    ```
    예: 문서의 이해도와 품질을 유지하기 위해  ...
    ```
* entitle = `제목을 붙이는`의 뜻으로 사용된 것 같습니다. :)
   ```
   예: 문서화 된 옵션은 제목으로 작성한 후 유형과 기본값을 추가합니다. 
   ```

2021-10-18 08:52 UTC, keipark commented on src/content/contribute/writers-guide.mdx
> +예제는 [EvalSourceMapDevToolPlugin's page의 `options` 섹션](/plugins/eval-source-map-dev-tool-plugin/#options)에서 찾을 수 있습니다.
`페이지`도 한글로 작성하면 좋을 것 같습니다~
* `EvalSourceMapDevToolPlugin's page의` > `EvalSourceMapDevToolPlugin 페이지의`

2021-10-28 06:29 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> + - [github username]
수정 완료했습니다!

2021-10-28 06:30 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> + - title: Title of Related Article
수정 완료했습니다!

2021-10-28 06:30 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +3. 변경 점들을 Pull Request에 생성하세요.
수정 완료했습니다!

2021-10-28 06:30 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +`related`는 페이지 하단에 **Further Reading** 섹션을 생성하고 `contributors`는 그 아래에 **Contributors** 섹션을 생성합니다. 글을 편집하고 인정받고 싶다면 주저하지 말고 GitHub 사용자 이름을 'contributors' 목록에 추가하세요.
수정 완료했습니다!

2021-10-28 06:30 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +- 로더는 역 따옴표로 묶여 있으며 [kebab-cased](https://en.wikipedia.org/w/index.php?title=Kebab_case): `css-loader`, `ts-loader`, …
수정 완료했습니다!

2021-10-28 06:30 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +플러그인을 사용 가능한 옵션 값 유형으로 표시하려면 'Plugin'의 camel-cased 형식의 제목을 사용하세요.
수정 완료했습니다!

2021-10-28 06:30 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +객체의 키가 동적이며 사용자 정의된 경우 ``를 사용하여 설명합니다.
수정 완료했습니다!

2021-10-28 06:31 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +- `sort`: 해당 섹션 (또는) 하위 섹션 내에서 이 글의 순서입니다.
수정 완료했습니다!

2021-10-28 06:31 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
>  + As we've learned in [production guide](/guides/production/)...
수정 완료했습니다!

2021-10-28 06:31 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +모든 것에 단순하다고 가정하지 마세요. 'just', 'simply'와 같은 단어를 피하세요.
수정 완료했습니다!

2021-10-28 12:19 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> + - [github username]
수정이 제대로 되지 않은것 같습니다.
원문과 비교변경사항으로 나오지 않아야합니다.

2021-10-28 12:19 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> + - title: Title of Related Article
수정이 제대로 되지 않은것 같습니다.
원문과 비교변경사항으로 나오지 않아야합니다.

2021-10-28 13:02 UTC, dkstyle commented on src/content/contribute/writers-guide.mdx
> +예제는 [EvalSourceMapDevToolPlugin's 페이지의 `options` 섹션](/plugins/eval-source-map-dev-tool-plugin/#options)에서 찾을 수 있습니다.
`EvalSourceMapDevToolPlugin's 페이지의` -> `EvalSourceMapDevToolPlugin 페이지의`

2021-10-28 13:06 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> + - [github username]
재수정하였습니다! 이제 비교변경사항으로 나오지 않습니다!

2021-10-28 13:08 UTC, angrymusic commented on src/content/contribute/writers-guide.mdx
> +예제는 [EvalSourceMapDevToolPlugin's 페이지의 `options` 섹션](/plugins/eval-source-map-dev-tool-plugin/#options)에서 찾을 수 있습니다.
수정했습니다!

2021-10-28 13:13 UTC, dkstyle approved these changes

2021-10-30 07:29 UTC, YukJiSoo approved these changes

2021-11-01 01:49 UTC, keipark approved these changes
👍

2021-11-01 01:52 UTC, merged