Tranlate module-federation-plugin.mdx
line/webpack.kr pull request #420
Opened 2021-11-08 14:14 UTC by dlskawo0409

## Summary 

// I#7

## 리뷰 참고 사항

// 다시 pull request 했습니다.

2021-11-10 06:35 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +이 구문을 사용하면 패키지 이름만 있는 라이브러리를 공유할 수 있습니다. 이 접근 방식은 프로토타이핑에 적합하지만 'react' 및 'react-dom'과 같은 라이브러리에 추가 요구 사항이 필요하기 때문에 대규모 프로덕션 환경으로 확장할 수 없습니다.
'react', 'react-dom'  > 원문의 백틱을 유지해주세요.

2021-11-10 06:35 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +      // package.json으로부터 버전 추론합니다.
* lodash  > 원문대로 따옴표 없이 유지하면 좋을것 같습니다.
* 버전 추론합니다 > 조사를 추가하여 `버전을 추론합니다.` 가 조금 더 자연스러울 것 같아요!

2021-11-10 06:35 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +이 구문을 사용하면 패키지 이름을 키로 정의하고, 값을 힌트[hints](#sharing-hints)가 포함된 개체로 정의하여 공유 동작을 수정하는 각 공유 패키지에 추가 힌트를 제공할 수 있습니다.
* 힌트의 `additional` 이란 표현이 번역에서 제외된 것 같습니다.
* `object` 개체 > 객체 
* 문장이 너무 길어서 해석하기 조금 어려운 것 같습니다. 아래처럼 문장을 분리하면 어떨까요?
````
// 예:
이 구문을 사용하면 각 공유 패키지에 힌트를 추가로 제공할 수 있습니다. 패키지의 이름을 키로, 공유 동작을 수정하기 위한 힌트를 포함한 객체를 값으로 정의하여 제공합니다.
````

2021-11-10 06:35 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +이 힌트를 사용하면 webpack이 비동기식 요청을 통해 라이브러리를 가져오는 대신 제공된 및 대체 모듈을 직접 포함할 수 있습니다. 즉, 초기 청크에서 이 공유 모듈을 사용할 수 있습니다. 또한 이 힌트가 활성화되면 제공된 모든 모듈과 대체 모듈이 항상 다운로드된다는 점에 주의하십시오.
* `제공된 및 대체 모듈` > `제공된 모듈이나 대체 모듈`처럼 풀어서 작성해주는 것은 어떨까요?
* `주의하십시오` > 번역 톤을 맞추면 좋을 것 같습니다~ (예: 주의하세요, 주의하기 바랍니다.)

2021-11-10 06:35 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +제공된 모듈은 공유 유효범위에 배치되어야 합니다. 이 제공된 모듈은 공유 유효범위에 공유 모듈이 없거나 버전이 유효하지 않은 경우 대체 모듈 역할도 합니다. (이 힌트의 값은 기본적으로 속성 이름으로 설정됩니다.)
* `property` > `프로퍼티`로 맞추어 번역하고 있습니다. Glossary를 참고해주세요
* https://github.com/line/webpack.kr/wiki/Glossary

2021-11-10 06:35 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +‘strictVersion’를 사용하면 버전이 유효하지 않은 경우 webpack이 공유 모듈을 거부할 수 있습니다(로컬 폴백 모듈을 사용할 수 있고 공유 모듈이 singleton이 아닌 경우 기본값은 true로 설정되고, 그렇지 않으면 false인 경우 필수 버전이 지정되지 않은 경우 효과가 없습니다).
* true, false 에 원문의 백틱을 유지해주세요.
* `그렇지 않으면 false인 경우` > 그렇지 않으면 `false`로 설정되며  ...가 조금 더 자연스러울 것 같습니다!

2021-11-12 07:44 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +이 힌트를 사용하면 webpack이 비동기식 요청을 통해 라이브러리를 가져오는 대신 제공된 모듈이나 대체 모듈을 직접 포함할 수 있습니다. 즉, 초기 청크에서 이 공유 모듈을 사용할 수 있습니다. 또한 이 힌트가 활성화되면 제공된 모든 모듈과 대체 모듈이 항상 다운로드된다는 점에 주의해야합니다.
띄어쓰기 확인부탁드려요~
* 주의해야합니다 > 주의해야 합니다.

2021-11-12 07:44 UTC, keipark commented on src/content/plugins/module-federation-plugin.mdx
> +          strictVersion: true, // 버전이 유효하지 않을 때 공유 버전을 사용하지 마십시오. fallback이 없는 Singleton 또는 모듈은 넘겨집니다. 그렇지 않으면 fallback이 사용됩니다.
* 마십시오: 번역톤을 맞추어 주세요.  (예: ~마세요, ~말아야 합니다)
* 문서내에서 fallback의 번역을 맞추어 주세요. (L162 폴백)

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +      // lodash을 공유모듈로 추가합니다.
lodash을 -> lodash를
공유모듈로 -> 공유 모듈로

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +      // 필요한 버전에 대한 버전 확인이 없습니다.
> 필요한 버전에 대한 버전 확인이 없습니다.

자연스럽게 읽히도록 버전이라는 단어의 반복을 제거할 수 있을 것 같아요!
```
ex) 필수 버전을 확인하지 않습니다.
```

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +        // lodash을 공유모듈로 추가합니다.
lodash을 -> lodash를
공유모듈로 -> 공유 모듈로

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +‘singleton’는 공유 범위에서 단일 버전의 공유 모듈만 허용합니다.(기본적으로 비활성화됨). 일부 라이브러리는 전역 내부 상태를 사용합니다.(예: react, react-dom). 따라서 한 번에 하나의 라이브러리 인스턴스만 실행하는 것이 중요합니다.
‘singleton’는 -> ‘singleton’은

---

마침표가 중복으로 추가되어있습니다. 하나를 제거해줘야 할 것 같아요!

- 허용합니다.(기본적으로 비활성화됨).
- 사용합니다.(예: react, react-dom).

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +‘strictVersion’를 사용하면 버전이 유효하지 않은 경우 webpack이 공유 모듈을 거부할 수 있습니다(로컬 폴백 모듈을 사용할 수 있고 공유 모듈이 singleton이 아닌 경우 기본값은 `true`로 설정되고, 그렇지 않으면 `false`로 설정되며 필수 버전이 지정되지 않은 경우 효과가 없습니다).
‘strictVersion’를 -> ‘strictVersion’을

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +      // vue를 공유모듈로 추가합니다.
공유모듈로 -> 공유 모듈로

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +      // package.json 으로부터 버전 추론합니다.
버전 추론합니다. ->  버전을 추론합니다.

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +      // vue를 공유모듈로 추가합니다.
공유모듈로 -> 공유 모듈로

2021-11-15 01:30 UTC, YukJiSoo commented on src/content/plugins/module-federation-plugin.mdx
> +      // vue를 공유모듈로 추가합니다.
공유모듈로 -> 공유 모듈로

2021-11-21 08:31 UTC, dkstyle requested changes

2021-11-21 08:31 UTC, dkstyle commented on src/content/plugins/module-federation-plugin.mdx
> +여러 공유 라이브러리의 버전을 지정하는 세 가지 방법이 있습니다.
`여러` 라는 표현은 제거하는게 자연스러울 것 같습니다.

2021-11-21 08:31 UTC, dkstyle commented on src/content/plugins/module-federation-plugin.mdx
> +이 구문은 패키지 이름을 키로 정의하고 버전([semver](https://semver.org/))을 값으로 정의할 수 있는 각 공유 라이브러리에 대한 더 많은 제어를 제공합니다.
어순을 조금 조정하면 더 자연스러울 것 같습니다.

ex)
이 구문을 사용하면 패키지 이름을 키로 정의하고 버전([semver](https://semver.org/))을 값으로 정의할 수 있는 각 공유 라이브러리를 보다 세부적으로 제어할 수 있습니다.

2021-11-21 08:31 UTC, dkstyle commented on src/content/plugins/module-federation-plugin.mdx
> +        // package.json 으로부터 버전 추론합니다.
버전 추론합니다. -> 버전을 추론합니다.

2021-11-21 08:31 UTC, dkstyle commented on src/content/plugins/module-federation-plugin.mdx
> +이 구문을 사용하면 각 공유 패키지에 힌트를 추가로 제공할 수 있습니다. 패키지의 이름을 키로, 공유 동작을 수정하기 위한 힌트를 포함한 객체를 값으로 정의하여 제공합니다.
제공합니다. -> 제공할 수 있습니다.

2021-11-21 08:31 UTC, dkstyle commented on src/content/plugins/module-federation-plugin.mdx
> +제공된 모듈의 버전입니다. webpack이 일치하는 낮은 버전을 대체할 수 있지만, 더 높은 버전은 대체할 수 없습니다.
webpack -> Webpack

2021-11-21 08:36 UTC, dkstyle commented
@dlskawo0409 리뷰 내용 확인 부탁드리고. [번역기여자 표시 방법 예시](https://github.com/line/webpack.kr/pull/440/files#diff-55f715c953dee51becb50178036430c6cd730e30d4e5742538d240d33538bdc3R21)를 참고해서 함께 작성해주세요.

2021-11-30 13:21 UTC, dkstyle commented on src/content/plugins/module-federation-plugin.mdx
> +          strictVersion: true, // 버전이 유효하지 않을 때 공유 버전을 사용하지 마십시오. fallback이 없는 Singleton 또는 모듈은 넘겨집니다. 그렇지 않으면 fallback이 사용됩니다.
@dlskawo0409 
162라인에는 `폴백`으로 번역되어 있고 238번 라인에는 `fallback`이라고 되어 있어서 이부분 한번 더 확인 부탁드립니다.

2021-12-02 13:49 UTC, dlskawo0409 commented on src/content/plugins/module-federation-plugin.mdx
> +          strictVersion: true, // 버전이 유효하지 않을 때 공유 버전을 사용하지 마십시오. fallback이 없는 Singleton 또는 모듈은 넘겨집니다. 그렇지 않으면 fallback이 사용됩니다.
162번 줄 폴백을 fallback으로 바꾸어 238번 줄과 맞추었습니다.

2021-12-02 13:54 UTC, dkstyle approved these changes

2021-12-03 02:26 UTC, choilim approved these changes

2021-12-06 07:10 UTC, YukJiSoo approved these changes

2021-12-06 09:26 UTC, keipark approved these changes

2021-12-06 09:28 UTC, merged