[Translation] plugins/watch-ignore-plugin.mdx
line/webpack.kr pull request #439
Opened 2021-11-12 03:58 UTC by KiKi-Daehaksaeng

## Summary 

#436

## 리뷰 참고 사항

## Glossary

regular expression 정규 표현식
RegExp : 정규 표현식

2021-11-12 07:58 UTC, keipark commented on src/content/plugins/watch-ignore-plugin.mdx
> +[읽기 모드](/configuration/watch)인 경우, 제공된 경로나 정규 표현식같은 지정된 파일을 무시하세요.
* 읽기 모드: 연결된 https://webpack.kr/configuration/watch/ 에서 `watch 모드`로 작성하고 있으므로 맞추면 좋을 것 같습니다.
* `경로나 정규 표현식에 매칭된 파일`을 무시하는 것 이므로 조금 더 자세하게 작성해주시면 좋을 것 같습니다~
   ```
    // 예:
    제공된 경로나 정규 표현식에 해당되는 특정 파일을 무시합니다.
   ```

2021-11-12 07:58 UTC, keipark commented on src/content/plugins/watch-ignore-plugin.mdx
> +- `paths` (`Array<string | RegExp>`): 정규 표현식이나 절대 경로의 목록에서 디렉터리나 무시되어야 할 파일까지의 경로.
`정규 표현식 또는 무시되어야하는 디렉터리나 파일의 절대 경로 목록`과 같은 표현이 조금 더 알맞을 것 같습니다. :)

2021-11-12 08:34 UTC, KiKi-Daehaksaeng commented on src/content/plugins/watch-ignore-plugin.mdx
> +- `paths` (`Array<string | RegExp>`): 정규 표현식이나 절대 경로의 목록에서 디렉터리나 무시되어야 할 파일까지의 경로.
지적해주신 사항 수정했습니다.
검토해주셔서 감사합니다.

2021-11-13 08:45 UTC, dkstyle requested changes

2021-11-13 08:45 UTC, dkstyle commented on src/content/plugins/watch-ignore-plugin.mdx
> +[watch 모드](/configuration/watch)인 경우, 제공된 경로나 정규 표현식에 해당되는 특정정 파일을 무시합니다다.
짧은 내용인 만큼, PR 내용을 꼼꼼하게 확인해주세요.
오타 수정 부탁드립니다. 

`특정정` 
`무시합니다다.`

2021-11-13 08:45 UTC, dkstyle commented on src/content/plugins/watch-ignore-plugin.mdx
> +- `paths` (`Array<string | RegExp>`): 정규 표현식 또는 무시되어야 하는 디렉터리나 파일까지의 경로 목록.
우선 원문의 절대경로(absolute paths)에 대한 내용이 누락되었습니다. 

구문의 파라미터가 Array<string | RegExp>로 되어있는 것으로 보아
`무시해야 하는 디렉터리나 파일에 대한 정규표현식 또는 절대 경로의 목록입니다. ` 와 같은 표현으로 되어야 하지 않을까요?

2021-11-13 10:35 UTC, KiKi-Daehaksaeng commented on src/content/plugins/watch-ignore-plugin.mdx
> +- `paths` (`Array<string | RegExp>`): 정규 표현식 또는 무시되어야 하는 디렉터리나 파일까지의 경로 목록.
수정했습니다. 감사합니다.

2021-11-14 11:57 UTC, dkstyle approved these changes

2021-11-15 00:35 UTC, choilim approved these changes

2021-11-15 02:26 UTC, YukJiSoo approved these changes

2021-11-15 05:19 UTC, merged