fix: Remove duplicated mode.md
line/webpack.kr pull request #64
Opened 2021-07-01 11:45 UTC by 1ilsang

## Summary 

![DOCUMENTATION](https://user-images.githubusercontent.com/23524849/124119039-f5eb4a00-daac-11eb-9158-3bcc316baf24.png)

- 중복되는 mode 문서 삭제: `mode.md`, `mode.mdx`

## 질문

[현재 번역된 페이지](https://webpack.kr/configuration/mode/#mode-development) 기준과 [webpack-upstream-master](https://github.com/webpack/webpack.js.org/blob/master/src/content/configuration/mode.mdx)의 코드영역 diff 가 다릅니다.

번역된 문서를 기준으로 mdx 로 놓았는데요, 확인 부탁드리겠습니다.

2021-07-01 15:46 UTC, dkstyle commented
@1ilsang 확인 감사합니다. 
mode.md -> mode.mdx 변경과 내용 수정이 있었습니다.

원문 [mode.mdx](https://raw.githubusercontent.com/webpack/webpack.js.org/master/src/content/configuration/mode.mdx) 내용과 맞추기 위한 [Sync PR](https://github.com/line/webpack.kr/pull/19/files#diff-10a9ba33de1de96311ee694fadb2d7ecd8c95cedfa0c795cfec642197757733b) 

mode.md 파일은 이름 변경되어 제거되는 것이 맞고. mode.mdx 내용은 일부 번역 누락된 내용이 있어 누락 내용만 추가 해야할 것 같습니다. 올려주신 내용은 outdated mode.md의 내용이 반영된 것으로 보입니다.

2021-07-01 15:58 UTC, dkstyle requested changes

2021-07-01 15:58 UTC, dkstyle commented on src/content/configuration/mode.mdx
> ++ mode: 'development'
https://github.com/webpack/webpack.js.org/blob/master/src/content/configuration/mode.mdx 에서 제거 된 내용이 맞습니다.

2021-07-01 15:58 UTC, dkstyle commented on src/content/configuration/mode.mdx
> +```diff
diff 에서 js로 변경된 것이 맞습니다.

2021-07-01 15:58 UTC, dkstyle commented on src/content/configuration/mode.mdx
> +```diff
production 부분도 마찬가지로 현재 내용들을 유지하는것이 맞습니다.
https://github.com/webpack/webpack.js.org/blob/master/src/content/configuration/mode.mdx

2021-07-01 15:58 UTC, dkstyle commented on src/content/configuration/mode.mdx
> -```js
(위와  동일) 현재 내용 유지

2021-07-01 16:30 UTC, 1ilsang commented
@dkstyle 
> https://github.com/line/webpack.kr/pull/64/files#diff-10a9ba33de1de96311ee694fadb2d7ecd8c95cedfa0c795cfec642197757733bL41 에서 and 제거

해당 작업에서 쉼표 뒤 띄어쓰기가 존재하지 않아 추가해 주었습니다.

2021-07-02 01:11 UTC, dkstyle approved these changes
👍

2021-07-07 02:25 UTC, choilim approved these changes

2021-07-07 06:03 UTC, keipark approved these changes

2021-07-07 11:18 UTC, merged